In [1341]:
import pandas as pd

In [1342]:
manual_df = pd.read_excel("D:\DA - Madhuri Gosavi\Mobile Consumer Preferences Analysis\Data\Survey fillup.xlsx")

In [1343]:
online_df = pd.read_excel("D:\DA - Madhuri Gosavi\Mobile Consumer Preferences Analysis\Data\Survey Responses.xlsx")

In [1344]:
manual_df.head()

,Name,Age,Gender,Residential Area,Specify Residential Area(village/ city / town name),Highest education level,Employment Status,Monthly Income (Self/Family if Unemployed),Current Smartphone brand,Smartphone model,...,Where do you prefer to buy your smartphone?,Do you consider resale value while purchasing a smartphone?,Are you satisfied with your current smartphone,Which smartphone brand would you like to buy next? ( enter smartphone brand you like),What will be the most important factor in your next smartphone purchase?,What is your expected budget for your next smartphone?,Would you consider buying a foldable smartphone in the future ?,Do you prefer Indian smartphone brands over foreign brands?,Any additional comments on smartphone buying experience or expectations /,Email Address
0,Surekha Nandre,41,F,Rural,Chhadvel,3,2,2,redmi,redmi 6,...,1.0,2.0,yes,SamsunggS25,5.0,3.0,2.0,1.0,NaN,NaN
1,rajput himani,20,F,Rural,bhorkheda,3,1,2,vivo,vivo y20,...,2.0,1.0,2,vivo 20s,4.0,2.0,3.0,3.0,NaN,NaN
2,rajput sanyogita,20,F,Rural,takarkhada,3,1,3,vivo,vivo y200e 5G,...,2.0,2.0,1,oneplus,3.0,3.0,2.0,1.0,NaN,NaN
3,lalit jadhav,30,M,Rural,rami,4,2,2,vivo,vivo y73,...,2.0,1.0,2,sumsung galaxy,6.0,3.0,3.0,3.0,NaN,NaN
4,vishakha rajput,21,F,Rural,pathare,4,1,2,realmi,realmi narzo 50a,...,2.0,2.0,1,oppo y22,4.0,3.0,2.0,1.0,NaN,NaN

In [1345]:
online_df.head()

,Timestamp,Age Group/ वयोगट :,Gender/ लिंग :,Residential Area/ निवासी क्षेत्र :,Employment Status/ रोजगार स्थिती:,Monthly Income (Self/Family if Unemployed)/ मासिक उत्पन्न (स्वतः/कुटुंब बेरोजगार असल्यास) :,Which smartphone brand are you currently using?/ तुम्ही सध्या कोणता स्मार्टफोन ब्रँड वापरत आहात?,Price Range of Your Current Smartphone/ तुमच्या सध्याच्या स्मार्टफोनची किंमत श्रेणी :,How long have you been using this smartphone?/ तुम्ही किती दिवसांपासून हा स्मार्टफोन वापरत आहात?,Where did you buy your smartphone?/ तुम्ही तुमचा स्मार्टफोन कोठे विकत घेतला?,...,Email Address,Column 22,Column 22.1,Column 10,Column 10.1,Column 10.2,Column 10.3,Column 10.4,Column 10.5,Column 10.6
0,2025-02-06 16:42:45.778,36 – 50,Female,Rural (village),Student,"Below ₹10,000",Nokia,"₹20,000 – ₹40,000",Less than 6 months,"Online (Amazon, Flipkart, etc.)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-02-06 17:00:19.916,18 – 25,Male,Urban (city/town),Student,"Below ₹10,000",Xiaomi,"₹10,000 – ₹20,000",6 months – 1 year,Local Retail Store,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-02-06 17:26:43.284,18 – 25,Female,Rural (village),Student,"₹25,000 – ₹50,000",Xiaomi/ Redmi,"₹10,000 – ₹20,000",More than 2 years,Local Retail Store,...,gosavimadhuri95@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-02-06 18:08:43.843,18 – 25,Male,Rural (village),Self-Employed,"₹25,000 – ₹50,000",Oppo,"Below ₹10,000",More than 3 years,Local Retail Store,...,viru88018@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-02-06 19:22:28.354,18 – 25,Female,Rural (village),Student,"₹25,000 – ₹50,000",Realme,"₹10,000 – ₹20,000",More than 3 years,"Online (Amazon, Flipkart, etc.)",...,patilvasudha353@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1346]:
manual_df = manual_df.loc[:, ~manual_df.columns.str.contains('^Unnamed|^Column', case=False)]
online_df = online_df.loc[:, ~online_df.columns.str.contains('^Unnamed|^Column', case=False)]

In [1347]:
# manual_df = manual_df.dropna(axis=1, how='all')
online_df = online_df.dropna(axis=1, how='all')

In [1348]:
manual_df.columns

Index(['Name', 'Age ', 'Gender', 'Residential Area',
       'Specify Residential Area(village/ city / town name)',
       'Highest education level ', 'Employment Status',
       'Monthly Income (Self/Family if Unemployed)',
       'Current Smartphone  brand', 'Smartphone model',
       'Current Smartphone Price  ',
       'How long have you been using this smartphone?',
       'Where did you buy your smartphone?',
       'What were the top 3 reasons for choosing this Smartphone?',
       'Which feature you use the most in your smartphone?',
       'How often do you upgrade your smartphone?',
       'Where do you prefer to buy your smartphone?',
       'Do you consider resale value while purchasing a smartphone?',
       'Are you satisfied with your current smartphone',
       'Which smartphone brand would you like to buy next? ( enter smartphone brand you like)',
       'What will be the most important factor in your next smartphone purchase?',
       'What is your expected budget for your next smartphone?',
       'Would you consider buying a foldable smartphone in the future ?',
       'Do you prefer Indian smartphone brands over foreign brands?',
       'Any additional comments on smartphone buying experience or expectations / ',
       'Email Address'],
      dtype='object')

In [1349]:
manual_df.rename(columns={
    'Name': 'name',
    'Age ': 'age_group',
    'Gender': 'gender',
    'Residential Area': 'residential_area',
    'Specify Residential Area(village/ city / town name)': 'location_name',
    'Highest education level ': 'education_level',
    'Employment Status': 'employment_status',
    'Monthly Income (Self/Family if Unemployed)': 'monthly_income',
    'Current Smartphone  brand': 'current_brand',
    'Smartphone model': 'model_name',
    'Current Smartphone Price  ': 'current_price_range',
    'How long have you been using this smartphone?': 'usage_duration',
    'Where did you buy your smartphone?': 'purchase_source',
    'What were the top 3 reasons for choosing this Smartphone?': 'top_3_reasons',
    'Which feature you use the most in your smartphone?': 'most_used_feature',
    'How often do you upgrade your smartphone?': 'upgrade_frequency',
    'Where do you prefer to buy your smartphone?': 'purchase_preference',
    'Do you consider resale value while purchasing a smartphone?': 'resale_consideration',
    'Are you satisfied with your current smartphone': 'satisfaction',
    'Which smartphone brand would you like to buy next? ( enter smartphone brand you like)': 'next_brand_preference',
    'What will be the most important factor in your next smartphone purchase?': 'next_priority',
    'What is your expected budget for your next smartphone?': 'next_budget',
    'Would you consider buying a foldable smartphone in the future ?': 'foldable_interest',
    'Do you prefer Indian smartphone brands over foreign brands?': 'indian_brand_preference',
    'Any additional comments on smartphone buying experience or expectations / ': 'comments',
    'Email Address': 'email'
}, inplace=True)

In [1350]:
manual_df

,name,age_group,gender,residential_area,location_name,education_level,employment_status,monthly_income,current_brand,model_name,...,purchase_preference,resale_consideration,satisfaction,next_brand_preference,next_priority,next_budget,foldable_interest,indian_brand_preference,comments,email
0,Surekha Nandre,41,F,Rural,Chhadvel,3,2,2,redmi,redmi 6,...,1.0,2.0,yes,SamsunggS25,5.0,3.0,2.0,1.0,NaN,NaN
1,rajput himani,20,F,Rural,bhorkheda,3,1,2,vivo,vivo y20,...,2.0,1.0,2,vivo 20s,4.0,2.0,3.0,3.0,NaN,NaN
2,rajput sanyogita,20,F,Rural,takarkhada,3,1,3,vivo,vivo y200e 5G,...,2.0,2.0,1,oneplus,3.0,3.0,2.0,1.0,NaN,NaN
3,lalit jadhav,30,M,Rural,rami,4,2,2,vivo,vivo y73,...,2.0,1.0,2,sumsung galaxy,6.0,3.0,3.0,3.0,NaN,NaN
4,vishakha rajput,21,F,Rural,pathare,4,1,2,realmi,realmi narzo 50a,...,2.0,2.0,1,oppo y22,4.0,3.0,2.0,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,Aniket mali,22,m,Rural,fagne,4,1,2,redmi,redmi 9 prime,...,4.0,4.0,yes,samsung,5.0,4.0,2.0,2.0,no,NaN
97,Himanshu chaudhari,25,m,Rural,varkhadi,1,3,1,vivo,vivo,...,1.0,1.0,yes,iphone 16,3.0,4.0,1.0,2.0,additional feature for gaming,NaN
98,yug chaudhari,26,f,Rural,Varkhadi,3,3,2,samsung,samsung,...,2.0,1.0,no,google pixel,2.0,1.0,3.0,3.0,no,NaN
99,viraj Gavdi,24,f,urbal,Dhule,4,4,4,oppo,oppo a54,...,1.0,3.0,no,google pixel,1.0,2.0,3.0,1.0,no,NaN
100,vedant patil,25,f,Rural,varkhadi,2,2,3,oppo,oppo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1351]:
online_df.columns

Index(['Timestamp', 'Age Group/ वयोगट :', 'Gender/ लिंग :',
       'Residential Area/ निवासी क्षेत्र :',
       'Employment Status/ रोजगार स्थिती:',
       'Monthly Income (Self/Family if Unemployed)/ मासिक उत्पन्न (स्वतः/कुटुंब बेरोजगार असल्यास) :',
       'Which smartphone brand are you currently using?/ तुम्ही सध्या कोणता स्मार्टफोन ब्रँड वापरत आहात?',
       'Price Range of Your Current Smartphone/ तुमच्या सध्याच्या स्मार्टफोनची किंमत श्रेणी :',
       'How long have you been using this smartphone?/ तुम्ही किती दिवसांपासून हा स्मार्टफोन वापरत आहात?',
       'Where did you buy your smartphone?/ तुम्ही तुमचा स्मार्टफोन कोठे विकत घेतला?',
       'What were the top 3 reasons for choosing this Smartphone?(Select upto 3)/ हा स्मार्टफोन निवडण्याची प्रमुख ३ कारणे कोणती होती? (३ पर्यंत निवडा)',
       'How often do you upgrade your smartphone?तुम्ही तुमचा स्मार्टफोन किती वेळेत बदलतात?',
       'Where do you prefer to buy your smartphone?/ तुम्ही तुमचा स्मार्टफोन कोठे खरेदी करण्यास प्राधान्य देता?',
       'Do you consider resale value while purchasing a smartphone? (Some people buy phones that have a good resale value so they can sell them later at a higher price. Do you consider this when choosing a smartphone?)/ काही लोक चांगले पुनर्विक्री मूल्य असलेले फोन विकत घेतात जेणेकरून ते नंतर ते जास्त किंमतीला विकू शकतील. स्मार्टफोन निवडताना तुम्ही याचा विचार करता का?',
       'What will be the most important factor in your next smartphone purchase?/ तुमच्या पुढील स्मार्टफोन खरेदीमध्ये सर्वात महत्त्वाचा घटक कोणता असेल?',
       'Would you consider buying a foldable smartphone in the future ?/ तुम्ही भविष्यात फोल्डेबल स्मार्टफोन खरेदी करण्याचा विचार कराल का?',
       'Do you prefer Indian smartphone brands over foreign brands?/ तुम्ही विदेशी ब्रँडपेक्षा भारतीय स्मार्टफोन ब्रँडला प्राधान्य देता का?',
       'Are you satisfied with your current smartphone /तुम्ही तुमच्या सध्याच्या स्मार्टफोनबाबत समाधानी आहात का?',
       'Which smartphone brand would you like to buy next? ( enter smartphone brand you like)/ तुम्हाला पुढील कोणता स्मार्टफोन ब्रँड खरेदी करायला आवडेल? (आपल्या आवडीचा स्मार्टफोन ब्रँड प्रविष्ट करा)',
       'Any additional comments on smartphone buying experience or expectations / स्मार्टफोन खरेदीचा अनुभव किंवा अपेक्षांवर कोणत्याही अतिरिक्त टिप्पण्या:',
       'What is the model name of your smartphone?/ तुमच्या स्मार्टफोनचे मॉडेल नाव काय आहे?',
       'Highest education level / उच्चतम शिक्षण पातळी',
       'What is your expected budget for your next smartphone?/ तुमच्या पुढील स्मार्टफोनसाठी तुमचे अपेक्षित बजेट किती आहे?',
       'Which feature you use the most in your smartphone?/ तुम्ही तुमच्या स्मार्टफोनमध्ये कोणते फिचर सर्वाधिक वापरता?',
       'Specify Residential Area(village/ city / town name)/निवासी क्षेत्र निर्दिष्ट करा (गाव / नगर / शहराचे नाव)',
       'Email Address'],
      dtype='object')

In [1352]:
online_df.rename(columns={
    'Timestamp': 'timestamp',
    'Age Group/ वयोगट :': 'age_group',
    'Gender/ लिंग :': 'gender',
    'Residential Area/ निवासी क्षेत्र :': 'residential_area',
    'Employment Status/ रोजगार स्थिती:': 'employment_status',
    'Monthly Income (Self/Family if Unemployed)/ मासिक उत्पन्न (स्वतः/कुटुंब बेरोजगार असल्यास) :': 'monthly_income',
    'Which smartphone brand are you currently using?/ तुम्ही सध्या कोणता स्मार्टफोन ब्रँड वापरत आहात?': 'current_brand',
    'Price Range of Your Current Smartphone/ तुमच्या सध्याच्या स्मार्टफोनची किंमत श्रेणी :': 'current_price_range',
    'How long have you been using this smartphone?/ तुम्ही किती दिवसांपासून हा स्मार्टफोन वापरत आहात?': 'usage_duration',
    'Where did you buy your smartphone?/ तुम्ही तुमचा स्मार्टफोन कोठे विकत घेतला?': 'purchase_source',
    'What were the top 3 reasons for choosing this Smartphone?(Select upto 3)/ हा स्मार्टफोन निवडण्याची प्रमुख ३ कारणे कोणती होती? (३ पर्यंत निवडा)': 'top_3_reasons',
    'How often do you upgrade your smartphone?तुम्ही तुमचा स्मार्टफोन किती वेळेत बदलतात?': 'upgrade_frequency',
    'Where do you prefer to buy your smartphone?/ तुम्ही तुमचा स्मार्टफोन कोठे खरेदी करण्यास प्राधान्य देता?': 'purchase_preference',
    'Do you consider resale value while purchasing a smartphone? (Some people buy phones that have a good resale value so they can sell them later at a higher price. Do you consider this when choosing a smartphone?)/ काही लोक चांगले पुनर्विक्री मूल्य असलेले फोन विकत घेतात जेणेकरून ते नंतर ते जास्त किंमतीला विकू शकतील. स्मार्टफोन निवडताना तुम्ही याचा विचार करता का?': 'resale_consideration',
    'What will be the most important factor in your next smartphone purchase?/ तुमच्या पुढील स्मार्टफोन खरेदीमध्ये सर्वात महत्त्वाचा घटक कोणता असेल?': 'next_priority',
    'Would you consider buying a foldable smartphone in the future ?/ तुम्ही भविष्यात फोल्डेबल स्मार्टफोन खरेदी करण्याचा विचार कराल का?': 'foldable_interest',
    'Do you prefer Indian smartphone brands over foreign brands?/ तुम्ही विदेशी ब्रँडपेक्षा भारतीय स्मार्टफोन ब्रँडला प्राधान्य देता का?': 'indian_brand_preference',
    'Are you satisfied with your current smartphone /तुम्ही तुमच्या सध्याच्या स्मार्टफोनबाबत समाधानी आहात का?': 'satisfaction',
    'Which smartphone brand would you like to buy next? ( enter smartphone brand you like)/ तुम्हाला पुढील कोणता स्मार्टफोन ब्रँड खरेदी करायला आवडेल? (आपल्या आवडीचा स्मार्टफोन ब्रँड प्रविष्ट करा)': 'next_brand_preference',
    'Any additional comments on smartphone buying experience or expectations / स्मार्टफोन खरेदीचा अनुभव किंवा अपेक्षांवर कोणत्याही अतिरिक्त टिप्पण्या:': 'comments',
    'What is the model name of your smartphone?/ तुमच्या स्मार्टफोनचे मॉडेल नाव काय आहे?': 'model_name',
    'Highest education level / उच्चतम शिक्षण पातळी': 'education_level',
    'What is your expected budget for your next smartphone?/ तुमच्या पुढील स्मार्टफोनसाठी तुमचे अपेक्षित बजेट किती आहे?': 'next_budget',
    'Which feature you use the most in your smartphone?/ तुम्ही तुमच्या स्मार्टफोनमध्ये कोणते फिचर सर्वाधिक वापरता?': 'most_used_feature',
    'Specify Residential Area(village/ city / town name)/निवासी क्षेत्र निर्दिष्ट करा (गाव / नगर / शहराचे नाव)': 'location_name',
    'Email Address': 'email'
}, inplace=True)

In [1353]:
online_df

,timestamp,age_group,gender,residential_area,employment_status,monthly_income,current_brand,current_price_range,usage_duration,purchase_source,...,indian_brand_preference,satisfaction,next_brand_preference,comments,model_name,education_level,next_budget,most_used_feature,location_name,email
0,2025-02-06 16:42:45.778,36 – 50,Female,Rural (village),Student,"Below ₹10,000",Nokia,"₹20,000 – ₹40,000",Less than 6 months,"Online (Amazon, Flipkart, etc.)",...,Doesn't matter,Yes,Oppo,NaN,Redmi note. 6 pro,Below 10th,"₹10,000 – ₹20,000",Web browsing,NaN,NaN
1,2025-02-06 17:00:19.916,18 – 25,Male,Urban (city/town),Student,"Below ₹10,000",Xiaomi,"₹10,000 – ₹20,000",6 months – 1 year,Local Retail Store,...,Yes,No,No,No,Redmi,Graduate,"₹20,000 – ₹40,000",Social media,Dahule,NaN
2,2025-02-06 17:26:43.284,18 – 25,Female,Rural (village),Student,"₹25,000 – ₹50,000",Xiaomi/ Redmi,"₹10,000 – ₹20,000",More than 2 years,Local Retail Store,...,Yes,Yes,One plus,NaN,Redmi Note 6 Pro,Graduation,"₹20,000 – ₹40,000",Web browsing,Vikhran,gosavimadhuri95@gmail.com
3,2025-02-06 18:08:43.843,18 – 25,Male,Rural (village),Self-Employed,"₹25,000 – ₹50,000",Oppo,"Below ₹10,000",More than 3 years,Local Retail Store,...,Yes,No,Yes,No,2020,Graduation,"Below 10,000",Other,NaN,viru88018@gmail.com
4,2025-02-06 19:22:28.354,18 – 25,Female,Rural (village),Student,"₹25,000 – ₹50,000",Realme,"₹10,000 – ₹20,000",More than 3 years,"Online (Amazon, Flipkart, etc.)",...,Yes,Yes,Realme,NaN,Realme 5- pro,Graduation,"₹20,000 – ₹40,000",Communication,Nageshwar Bangala,patilvasudha353@gmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,2025-03-05 08:12:02.080,26 – 35,Male /पुरुष,Rural (village) /ग्रामीण (गाव),Self-Employed/ स्वयंरोजगार,"₹25,000 – ₹50,000",Vivo,"₹40,000 – ₹70,000",1 – 3 years/ 1-3 वर्षे,Brand Outlet/Showroom/ ब्रँड आउटलेट/शोरूम,...,Yes/ हो,No/ नाही,Xiomi,NaN,Vivo v14,Graduation/ पदवी,"₹10,000 – ₹20,000",Web browsing/ वेब ब्राउझिंग,Dhule,ketansharma5634@gmail.com
255,2025-03-05 08:45:54.651,18 – 25,Male /पुरुष,Rural (village) /ग्रामीण (गाव),Employed / नोकरीला आहे,"₹25,000 – ₹50,000",Nokia,"₹10,000 – ₹20,000",1 – 3 years/ 1-3 वर्षे,Brand Outlet/Showroom/ ब्रँड आउटलेट/शोरूम,...,Doesn't matter/ फरक पडत नाही,No/ नाही,Vivo V50 Pro,NaN,Nokia K9,Graduation/ पदवी,"₹20,000 – ₹40,000",Social media/ सोशल मेडिया,Dhule,sarangdeore@gmail.com
256,2025-03-05 12:17:09.290,18 – 25,Female /स्त्री,Urban (city/town)/शहरी (शहर/नगर),Student/ विद्यार्थी,"₹10,000 – ₹25,000",Oppo,"₹10,000 – ₹20,000",1 – 3 years/ 1-3 वर्षे,Local Retail Store/ स्थानिक रिटेल स्टोअर,...,Yes/ हो,Yes/ होय,OPPO N1,For Great quality of software \n,oppo 1+,10th – 12th/ 10वी - 12वी,"₹10,000 – ₹20,000",Other/ इतर,Shirpur,praveen.girase79@gmail.com
257,2025-03-05 12:21:52.341,26 – 35,Female /स्त्री,Urban (city/town)/शहरी (शहर/नगर),Self-Employed/ स्वयंरोजगार,"₹50,000 – ₹1,00,000",OnePlus,"₹20,000 – ₹40,000",More than 3 years/ 3 वर्षांपेक्षा जास्त,Local Retail Store/ स्थानिक रिटेल स्टोअर,...,Yes/ हो,Yes/ होय,I phone,No,Oneplus nord 2 5G,Post-graduation & Above/ पदव्युत्तर आणि त्यावरील,"₹20,000 – ₹40,000",Communication/ संवाद,Dondaicha,harshnarawal95@gmail.com
258,2025-03-05 19:46:32.686,18 – 25,Female /स्त्री,Rural (village) /ग्रामीण (गाव),Student/ विद्यार्थी,"₹25,000 – ₹50,000",Xiaomi/ Redmi,"₹10,000 – ₹20,000",6 months – 1 year/ 6 महिने - 1 वर्ष,Local Retail Store/ स्थानिक रिटेल स्टोअर,...,Yes/ हो,Yes/ होय,Redmi,...,Redmi 13C,Graduation/ पदवी,"₹10,000 – ₹20,000",Social media/ सोशल मेडिया,Gondur,patilpayal8599@gmail.com

In [1354]:
manual_df['gender'].unique()

array(['F', 'M', 'f', 'm'], dtype=object)

In [1355]:
online_df['gender'].unique()

array(['Female', 'Male', 'Male /पुरुष', 'Female /स्त्री'], dtype=object)

In [1356]:
def clean_gender(value):
    if pd.isna(value):
        return None
    value = str(value).strip().lower()  
    if value in ['male', 'm', 'male /पुरुष']:
        return 'Male'
    elif value in ['female', 'f', 'female /स्त्री']:
        return 'Female'
    else:
        return 'Other'

# Apply to both
manual_df['gender'] = manual_df['gender'].apply(clean_gender)
online_df['gender'] = online_df['gender'].apply(clean_gender)

In [1357]:
manual_df['gender'].value_counts()

gender
Male      62
Female    39
Name: count, dtype: int64

In [1358]:
online_df['gender'].value_counts()

gender
Male      133
Female    126
Name: count, dtype: int64

In [1359]:
manual_df['residential_area'].unique()

array(['Rural', 'urban', 'Urban', 'Rural ', 'urbal', 'rural'],
      dtype=object)

In [1360]:
def clean_manual_area(value):
    if pd.isna(value):
        return None
    value = str(value).strip().lower()
    if 'urban' in value or 'urbal' in value:
        return 'Urban'
    elif 'rural' in value:
        return 'Rural'
    else:
        return 'Other'

manual_df['residential_area'] = manual_df['residential_area'].apply(clean_manual_area)

In [1361]:
manual_df['residential_area'].value_counts()

residential_area
Rural    52
Urban    49
Name: count, dtype: int64

In [1362]:
online_df['residential_area'].unique()

array(['Rural (village)', 'Urban (city/town)',
       'Rural (village) /ग्रामीण (गाव)',
       'Urban (city/town)/शहरी (शहर/नगर)'], dtype=object)

In [1363]:
def clean_online_area(value):
    if pd.isna(value):
        return None
    value =str(value).strip().lower()
    if 'urban (city/town)' in value  or 'urban (city/town)/शहरी (शहर/नगर)' in value:
        return 'Urban'
    elif 'rural (village)' in value or 'rural (village) /ग्रामीण (गाव)' in value:
        return 'Rural'
    else:
        return 'Other'

online_df['residential_area'] = online_df['residential_area'].apply(clean_online_area)

In [1364]:
online_df['residential_area'].value_counts()

residential_area
Rural    143
Urban    116
Name: count, dtype: int64

In [1365]:
manual_df['monthly_income'].unique()

array([2, 3, 4, 1], dtype=int64)

In [1366]:
manual_df['monthly_income']= manual_raw['Monthly Income (Self/Family if Unemployed)']

In [1367]:
income_map_manual = {
    1: 'Below 10,000',
    2: '10,000 - 25,000',
    3: '25,000 - 50,000',
    4: '50,000 - 1,00,000',
    5: 'Above 1,00,000'
}

manual_df['monthly_income'] = manual_df['monthly_income'].map(income_map_manual)

In [1368]:
manual_df['monthly_income'].value_counts()

monthly_income
10,000 - 25,000      36
25,000 - 50,000      32
50,000 - 1,00,000    20
Below 10,000         13
Name: count, dtype: int64

In [1369]:
online_df['monthly_income'].unique()

array(['Below ₹10,000', '₹25,000 – ₹50,000', '₹10,000 – ₹25,000',
       'Above ₹1,00,000', '₹50,000 – ₹1,00,000',
       'Below ₹10,000/ ₹10,000 च्या खाली',
       'Above ₹1,00,000/ ₹ 1,00,000 च्या वर'], dtype=object)

In [1370]:
def clean_monthly_income(value):
    if pd.isna(value):
        return None

    value = value.strip().lower()

    if 'below' in value or 'खाली' in value:
        return 'Below 10,000'
    elif '10,000' in value and '25,000' in value:
        return '10,000 - 25,000'
    elif '25,000' in value and '50,000' in value:
        return '25,000 - 50,000'
    elif '50,000' in value and '1,00,000' in value:
        return '50,000 - 1,00,000'
    elif 'above' in value or 'वर' in value:
        return 'Above 1,00,000'
    else:
        return None


online_df['monthly_income'] = online_df['monthly_income'].apply(clean_monthly_income)

In [1371]:
online_df['monthly_income'].value_counts()

monthly_income
10,000 - 25,000      87
25,000 - 50,000      76
Below 10,000         61
50,000 - 1,00,000    21
Above 1,00,000       14
Name: count, dtype: int64

In [1372]:
manual_df['current_brand'].unique()

array(['redmi', 'vivo', 'realmi', 'samsung', 'oppo', 'motorola', 'Narzo',
       'apple', 'oneplus', 'samsung ', 'panasonic', 'lava',
       'sumsung galaxy', 'iQoo', 'Redmi', 'Vivo', 'Xiomi', 'Google',
       'Huwei', 'Samsumg', 'Lava', 'Oppo', 'Samsung', 'Apple', 'Samsung ',
       'Vivo ', 'Poco', 'poco', 'iphone', 'one plus', 'Google pixel',
       'moto'], dtype=object)

In [1373]:
brand_map = {
    'samsung': 'Samsung',
    'samsung ': 'Samsung',
    'samsumg': 'Samsung',
    'sumsung galaxy': 'Samsung',
    
    'redmi': 'Xiaomi',
    'xiomi': 'Xiaomi',
    'realmi': 'Realme',
    
    'vivo': 'Vivo',
    'vivo ': 'Vivo',
    
    'oppo': 'Oppo',
    'oneplus': 'OnePlus',
    'one plus': 'OnePlus',
    
    'apple': 'Apple',
    'iphone': 'Apple',
    
    'google': 'Google',
    'google pixel': 'Google',
    
    'motorola': 'Motorola',
    'moto': 'Motorola',
    
    'iqoo': 'IQOO',
    'iqoo ': 'IQOO',
    
    'lava': 'Lava',
    'panasonic': 'Panasonic',
    'huwei': 'Huawei',
    'narzo': 'Realme',
    'poco': 'Poco',
}

def clean_brand(value):
    if pd.isna(value):
        return None
    value = str(value).strip().lower()
    for key in brand_map:
        if key in value:
            return brand_map[key]
    return value.title()  # fallback: capitalize unknowns

In [1374]:
manual_df['current_brand'] = manual_df['current_brand'].apply(clean_brand)

In [1375]:
print(manual_df['current_brand'].value_counts())

current_brand
Xiaomi       17
Vivo         17
Samsung      15
Realme       10
Oppo         10
Apple        10
OnePlus       5
Google        5
Motorola      3
Panasonic     2
Lava          2
Huawei        2
Poco          2
IQOO          1
Name: count, dtype: int64

In [1376]:
online_df['current_brand'].unique()

array(['Nokia', 'Xiaomi', 'Xiaomi/ Redmi', 'Oppo', 'Realme', 'Samsung',
       'Vivo', 'Other', 'OnePlus', 'Motorola', 'Apple', 'Google', 'IQOO'],
      dtype=object)

In [1377]:
def clean_online_brand(value):
    if pd.isna(value):
        return None
    value = value.strip().lower()
    
    brand_map = {
        'xiaomi/ redmi': 'Xiaomi',
        'xiaomi': 'Xiaomi',
        'redmi': 'Xiaomi',
        'nokia': 'Nokia',
        'oppo': 'Oppo',
        'realme': 'Realme',
        'samsung': 'Samsung',
        'vivo': 'Vivo',
        'oneplus': 'OnePlus',
        'motorola': 'Motorola',
        'apple': 'Apple',
        'google': 'Google',
        'iqoo': 'IQOO',
        'other': 'Other'
    }

    return brand_map.get(value, value.title())  # fallback: title case

In [1378]:
online_df['current_brand'] = online_df['current_brand'].apply(clean_online_brand)

In [1379]:
print(online_df['current_brand'].value_counts())

current_brand
Xiaomi      59
Realme      41
Oppo        36
Vivo        36
Samsung     24
Other       17
OnePlus     14
Apple       13
Motorola    12
Nokia        3
Google       2
IQOO         2
Name: count, dtype: int64

In [1380]:
manual_df['model_name'].unique()

array(['redmi 6', 'vivo y20', 'vivo y200e 5G', 'vivo y73',
       'realmi narzo 50a', 'realmi note 10', 'samsung s31', 'oppo y17',
       'vivo s22', 'motorola edge neo', 'oppo s53', nan,
       ' iphone 14 pro max', 'iphone 15 pro max', 'redmi12',
       'iphone 14 pro max', 'redmi6', 'samsung s51', 'realmi 10', 'pgo',
       'panasonic eluga 17', 'redmi not 14', 'lava agni',
       'samsung galaxy m13', 'inQoo zgx', 'realme N65', 'redmi 14c ',
       'motorola G45', 'redmi 13', 'redmi 84', 'oneplus nord 10',
       'realme 11 pro', 'Vivo V50', 'Xiomi 12', 'Redmi 13', 'Pixel 6',
       'Huawei Mate Pro', 'Samsung A25', 'Pixel 7', 'Lava A 13',
       'Vivo V13', 'Xiomi 14', 'Vivo V 12', 'Xiomi 10', 'Redmi 8 Prime',
       'Google pixel 8', 'Huwai P40', 'Oppo find x2', 'Oppo X3',
       'Vivo S6', 'Samsung Galaxy S6', 'Apple 16', 'Samsung Galaxy A56',
       'Apple 15', 'Samsung Galaxy S10', 'Huwei Mate 60', 'Galaxy S24',
       'Poco F1', 'samsung galaxy', 'poco', 'realmi 6', 'vivo V 14',
       'vivov 14', 'oppo a54', 'iphone 15', 'one plus nord 5', 'iphon 15',
       'Google pixel', 'samsung  galaxy 8', 'vivo v29', 'samsung',
       'iphone 16', 'v2336', 'motorola', 'redmi 9 prime', 'vivo', 'oppo'],
      dtype=object)

In [1381]:
def clean_model_name(value):
    if pd.isna(value):
        return None

    value = str(value).strip().lower()

    # Common typo corrections
    replacements = {
        'realmi': 'realme',
        'xiomi': 'xiaomi',
        'huwai': 'huawei',
        'inqoo': 'iqoo',
        'iphon': 'iphone',
        'not ': 'note ',
        'samsumg': 'samsung',
        'galaxy  ': 'galaxy ',
        'vivov': 'vivo v',
        'samsung  galaxy': 'samsung galaxy',
        'pgo': 'poco',
        'eluga 17': 'eluga i7'
    }

    for typo, correct in replacements.items():
        value = value.replace(typo, correct)

    # remove double spaces and extra whitespace
    value = ' '.join(value.split())

    return value

In [1382]:
manual_df['model_name'] = manual_df['model_name'].apply(clean_model_name)

In [1383]:
manual_df['model_name'].value_counts()

model_name
oppo a54              3
iphonee 15 pro max    3
redmi 6               2
vivo v50              2
redmi 13              2
                     ..
huawei mate pro       1
samsung a25           1
pixel 7               1
vivo y20              1
oppo                  1
Name: count, Length: 72, dtype: int64

In [1384]:
online_df['model_name'].unique()

array(['Redmi note. 6 pro', 'Redmi ', 'Redmi Note 6 Pro ', 2020,
       'Realme 5- pro', 'Oppo f27 pro plus 5 g ', 'Realme 7i',
       'Realme 8 5g', 'Samsung galaxy M02s ', 'Redmi note 10t 5g',
       'Redmi9prime', '....', 'Oppo A77', 'Vivo y16', 'Realme 6i',
       'M2006', 'Vivo Y200e 5G', 'Vivo Y28e 5G', 'Realme C53', 'Vivo V40',
       'Y20', 'Redmi note 7 pro', 'M6 5g pro', 'Vivo 1802',
       'Samsung f554', 'Redmi 9 prime', 'Nord CE', 'G64 5G',
       'Realme 10 Pro 5G', 'Y3', 21, 'vivo Y200e 5G', 'Realme 8i',
       'Redmi note 12 pro max', 'A 50', 'Poco', 'Oppo A1K', 'Redmi 13c',
       'Vivo v14', 'Realme 10 Pro', 'Oppo k12x ', 'Redmi 10 A', 'Poco m3',
       'A 17', '16pro max', 'Redmi note 13 pro plus', 'Vivo T2x 5g',
       'One plus c3 light ', 'Realme X7 5g', 'Oppo F17 Pro ', 'One plus',
       'A35 ', 'Redmi 12c', 'Moto g34 5g', 'iPhone 13', 'Redmi',
       'ओप्पो के 12 एक्स', 'N61', 'Y56 5g', 'Realme c25s', 'Vivo Y21',
       'Redmi 13 C', 'Moto edge 50 pro', 'Samsung f54', 'Realme Narzo 30',
       'Redmi 9', 'OnePlus Nord CE 2 lite 5G', 'Oppo12', 'redmi 9',
       'Vivo y21', 53, 'Tecno pop 8', 'Motorola g85', 'Samsung', 'T2x',
       'OppoA55', 'Redmi 8', 'Note 12', 'Oppo', 'kharde',
       'Redmi 10 Prime', 'G 85', 'Realme 12 5G', 'Pixel 6A', 'Redmi8a',
       'Techno', 'Poco c 61', 'Redmi9activ', 'Samsung m21', 'Realmi 8',
       'Neo 6 5G', 'Samsung ', 'Redmi note 8', 'G53', 'Vivo Y12',
       'Oppo a31', 'Realme 8', '14 Pro Max', 'iPhone 16pro',
       'Oppo Reno 10', 'realme', 'Narzo N55', 'Techna spark seven',
       'Realme ', 'Realme 8pro', 'iPhone 15 pro', 'Vivo Y20G',
       'Redmi note 9 pro max', 'X4 Pro 5g', 'Nokia c32', 'Y21 T', 'I9',
       'J7', 'Oppo f25 pro', 'Galaxy S 248', '1+', 'Samsung galaxy m42',
       'Moto', 'Redmi 10 prime', 'IPHONE 16 PRO', 'Redmi Note 9',
       'Onepluse nord 10', 'iPhone 16 pro max', 'Oppo f15', 'Realmi 10 ',
       'NORD 4', 'Redmi 6', 'One plus 2T5g', 'Oppo k12x 5G',
       'Redmi note 6', 'Oppo A15s', 'Realme C31', 'Vivio y20', 'Poco c61',
       'Samsung galaxy ', 'Realme', 'Vivo', 'Vivo Y16', 'I phone 11 ',
       'Y202', 'Realmi c35', 'Vivo y20', 'Motorola edge neo', 'Redmi9',
       'Realme c25', 'Y200', 'OnePlus nord Ce 5g', '2201117TI',
       'Redmi note 9', 'Mi Note 6', 'Vivo T2x 5g ', 'Oppo F21 pro 5g',
       'Note 4', 'iphone 15 ', 'OnePlus', 'Redmi y3', 'Y28 5g',
       'Razr 40 ultra', 'OnePlus nord ce4', 'Lava blaze x 5g', 'V2029',
       'Redemi 9power', 'Moto G64 5g', 'Oppo a15s', 'Oppo A77 ',
       'Vivo A53', 'Redmi 7', 'Vvo pro', 'Samsung galaxy note ',
       'Realmi note pro ', 'Redmi note5', 'Realme note', 'Redmi7',
       'iPhone 15', 'Realme C61', 'iPhone ', 'Samsung  j6+', 'Realms a50',
       'Y33T', 'Poco m4', 'A5', 'Redmi note 12', 'Oppo pro5g', 'Oppo F27',
       'Vivo 1606', 'Oppo A16', 'Poco c55', 'Realme 3', 'Samsung M12',
       '9 prime', 'Realme 12x 5G', 'Oppo A 31 ', 'Realme lab',
       'Redmi Mi ', 'Realme C65G', 'Realme 12x', 'SamsungA15',
       'Vivo y33t', 'Oppo A7', 'Samsung Galaxy S8+', 'galaxy a30s',
       'Google pixel 6', 'Redmi 18 pro', 'Tecno spark', 'A55',
       'Oppe reno 2z', 'Oppo Reno 6', 'Redmi9i', 'Motorola g64', 'Redme ',
       'Nothing ', 'Moto g64 ', 'Samsung F41', 'A35 5g', 'Motog65 5G',
       'Realme note 9', 'CPH1819', 'Iphone 16', 'Nokia K9', 'oppo 1+',
       'Oneplus nord 2 5G', 'Redmi 13C'], dtype=object)

In [1385]:
def clean_model_name(value):
    if pd.isna(value):
        return None

    value = str(value).strip().lower()

    # Fix common brand/model typos
    corrections = {
        'redemi': 'redmi',
        'redme': 'redmi',
        'realmi': 'realme',
        'oppe': 'oppo',
        'vivio': 'vivo',
        'iphon': 'iphone',
        'i phone': 'iphone',
        'samsumg': 'samsung',
        'vvo': 'vivo',
        'techna': 'tecno',
        'techno': 'tecno'
    }

    for typo, fix in corrections.items():
        value = value.replace(typo, fix)

    # Remove multiple spaces
    value = ' '.join(value.split())

    # Remove invalid/suspicious entries
    if value in ['....', '53', '2020', 'kharde', '1+', '21']:
        return None

    return value

In [1386]:
online_df['model_name'] = online_df['model_name'].apply(clean_model_name)

In [1387]:
online_df['model_name'].value_counts().head(20)

model_name
redmi 9           6
redmi             6
vivo y16          4
redmi note 9      4
redmi 6           3
oppo a77          3
samsung           3
realme 8          3
realme            3
samsung galaxy    3
redmi 8           3
redmi 13c         2
oppo a15s         2
redmi 12c         2
iphonee 13        2
vivo t2x 5g       2
vivo y20          2
iphonee 15        2
realme 7i         2
vivo v14          2
Name: count, dtype: int64

In [1388]:
manual_df['age_group'].unique()

array([41, 20, 30, 21, 50, 35, 37, 66, 28, 29, 24, 27, 45, 22, 19, 40, 26,
       23, 36, 25, 44, 18, 31, 38, 39], dtype=int64)

In [1389]:
def assign_age_group(age):
    if pd.isna(age):
        return None
    try:
        age = int(age)
    except:
        return None

    if age < 18:
        return 'Below 18'
    elif 18 <= age <= 25:
        return '18 - 25'
    elif 26 <= age <= 35:
        return '26 - 35'
    elif 36 <= age <= 50:
        return '36 - 50'
    else:
        return '50+'

In [1390]:
manual_df['age_group'] = manual_df['age_group'].apply(assign_age_group)

In [1391]:
manual_df['age_group'].value_counts()

age_group
18 - 25    58
26 - 35    30
36 - 50    12
50+         1
Name: count, dtype: int64

In [1392]:
online_df['age_group'].unique()

array(['36 – 50', '18 – 25', 'Below 18', '26 – 35', '50+'], dtype=object)

In [1393]:
map_age_group = {
    'Below 18' : 'Below 18',
    '18 – 25' : '18 - 25',
    '26 – 35' : '26 - 35',
    '36 – 50' : '36 - 50',
    '50+' : '50+'

}

online_df['age_group']= online_df['age_group'].map(map_age_group)

In [1394]:
online_df['age_group'].value_counts()

age_group
18 - 25     181
26 - 35      33
Below 18     22
36 - 50      20
50+           3
Name: count, dtype: int64

In [1395]:
manual_df

,name,age_group,gender,residential_area,location_name,education_level,employment_status,monthly_income,current_brand,model_name,...,purchase_preference,resale_consideration,satisfaction,next_brand_preference,next_priority,next_budget,foldable_interest,indian_brand_preference,comments,email
0,Surekha Nandre,36 - 50,Female,Rural,Chhadvel,3,2,"10,000 - 25,000",Xiaomi,redmi 6,...,1.0,2.0,yes,SamsunggS25,5.0,3.0,2.0,1.0,NaN,NaN
1,rajput himani,18 - 25,Female,Rural,bhorkheda,3,1,"10,000 - 25,000",Vivo,vivo y20,...,2.0,1.0,2,vivo 20s,4.0,2.0,3.0,3.0,NaN,NaN
2,rajput sanyogita,18 - 25,Female,Rural,takarkhada,3,1,"25,000 - 50,000",Vivo,vivo y200e 5g,...,2.0,2.0,1,oneplus,3.0,3.0,2.0,1.0,NaN,NaN
3,lalit jadhav,26 - 35,Male,Rural,rami,4,2,"10,000 - 25,000",Vivo,vivo y73,...,2.0,1.0,2,sumsung galaxy,6.0,3.0,3.0,3.0,NaN,NaN
4,vishakha rajput,18 - 25,Female,Rural,pathare,4,1,"10,000 - 25,000",Realme,realme narzo 50a,...,2.0,2.0,1,oppo y22,4.0,3.0,2.0,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,Aniket mali,18 - 25,Male,Rural,fagne,4,1,"10,000 - 25,000",Xiaomi,redmi 9 prime,...,4.0,4.0,yes,samsung,5.0,4.0,2.0,2.0,no,NaN
97,Himanshu chaudhari,18 - 25,Male,Rural,varkhadi,1,3,"Below 10,000",Vivo,vivo,...,1.0,1.0,yes,iphone 16,3.0,4.0,1.0,2.0,additional feature for gaming,NaN
98,yug chaudhari,26 - 35,Female,Rural,Varkhadi,3,3,"10,000 - 25,000",Samsung,samsung,...,2.0,1.0,no,google pixel,2.0,1.0,3.0,3.0,no,NaN
99,viraj Gavdi,18 - 25,Female,Urban,Dhule,4,4,"50,000 - 1,00,000",Oppo,oppo a54,...,1.0,3.0,no,google pixel,1.0,2.0,3.0,1.0,no,NaN
100,vedant patil,18 - 25,Female,Rural,varkhadi,2,2,"25,000 - 50,000",Oppo,oppo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1396]:
manual_df['education_level'].unique()

array([3, 4, 2, 1], dtype=int64)

In [1397]:
edu_mapping_manual = {
    1: 'Below 10th',
    2: '10th - 12th',
    3: 'Graduation',
    4: 'Post-graduation & Above'
}

manual_df['education_level'] = manual_df['education_level'].map(edu_mapping_manual)

In [1398]:
print(manual_df['education_level'].unique())

['Graduation' 'Post-graduation & Above' '10th - 12th' 'Below 10th']

In [1399]:
online_df['education_level'].unique()

array(['Below 10th', 'Graduate', 'Graduation', 'Post-graduation & Above',
       '10th – 12th', 'Graduation/ पदवी', '10th – 12th/ 10वी - 12वी',
       'Post-graduation & Above/ पदव्युत्तर आणि त्यावरील',
       'Below 10th / दहावीच्या खाली'], dtype=object)

In [1400]:
def clean_online_education(value):
    if pd.isna(value):
        return None
    val = value.strip().lower()
    if 'below 10' in val or 'दहावीच्या खाली' in val:
        return 'Below 10th'
    elif '10th' in val or '10वी' in val:
        return '10th - 12th'
    elif 'graduation' in val and 'post' not in val and 'पदवी' in val or val in ['graduation', 'graduate']:
        return 'Graduation'
    elif 'post' in val or 'पदव्युत्तर' in val:
        return 'Post-graduation & Above'
    else:
        return 'Other'

online_df['education_level']= online_df['education_level'].apply(clean_online_education)

In [1401]:
print(online_df['education_level'].unique())

['Below 10th' 'Graduation' 'Post-graduation & Above' '10th - 12th']

In [1402]:
manual_df['employment_status'].unique()

array([2, 1, 3, 4], dtype=int64)

In [1403]:
emp_status_mapping_manual = {
    1: 'Student',
    2: 'Employed',
    3: 'Self-Employed',
    4: 'Unemployed'
}

manual_df['employment_status'] = manual_df['employment_status'].map(emp_status_mapping_manual)

In [1404]:
manual_df['employment_status'].value_counts()

employment_status
Student          28
Unemployed       26
Employed         25
Self-Employed    22
Name: count, dtype: int64

In [1405]:
online_df['employment_status'].unique()

array(['Student', 'Self-Employed', 'Employed', 'Unemployed',
       'Employed / नोकरीला आहे', 'Student/ विद्यार्थी',
       'Self-Employed/ स्वयंरोजगार', 'Unemployed/ बेरोजगार'], dtype=object)

In [1406]:
def clean_online_employment_status(value):
    if pd.isna(value):
        return None
    val = value.strip().lower()
    
    if 'student' in val or 'विद्यार्थी' in val:
        return 'Student'
    elif 'self' in val or 'स्वयंरोजगार' in val:
        return 'Self-Employed'
    elif 'employed' in val or 'नोकरी' in val:
        return 'Employed'
    elif 'unemployed' in val or 'बेरोजगार' in val:
        return 'Unemployed'
    else:
        return 'Other'


online_df['employment_status'] = online_df['employment_status'].apply(clean_online_employment_status)

In [1407]:
online_df['employment_status'].value_counts()

employment_status
Student          169
Employed          57
Self-Employed     33
Name: count, dtype: int64

In [1408]:
manual_df['current_price_range'].unique()

array([1, 2, 3, 5, 4], dtype=int64)

In [1409]:
maping_mannual_price_range = {
    1:'Below 10,000',
    2:'10,000 - 20,000',
    3:'20,000 - 40,000',
    4:'40,000 - 70,000',
    5:'Above 70,000'
}
    
manual_df['current_price_range'] = manual_df['current_price_range'].map(maping_mannual_price_range)

In [1410]:
manual_df['current_price_range'].value_counts()

current_price_range
10,000 - 20,000    46
20,000 - 40,000    31
Below 10,000       10
40,000 - 70,000     9
Above 70,000        5
Name: count, dtype: int64

In [1411]:
online_df['current_price_range'].unique()

array(['₹20,000 – ₹40,000', '₹10,000 – ₹20,000', 'Below ₹10,000',
       'Above ₹70,000', 'Below ₹10,000 / ₹10,000 च्या खाली',
       '₹40,000 – ₹70,000', 'Above ₹70,000/   ₹70,000  च्या वरती'],
      dtype=object)

In [1412]:
def clean_online_price_range(value):
    if pd.isna(value):
        return None
    val = value.strip().lower()
    
    if 'below ₹10,000' in val or '₹10,000 च्या खाली' in val or '10000 च्या खाली' in val or 'below 10,000' in val:
        return 'Below 10,000'
    elif '₹10,000 – ₹20,000' in val:
        return '10,000 - 20,000'
    elif '₹20,000 – ₹40,000' in val:
        return '20,000 - 40,000'
    elif '₹40,000 – ₹70,000' in val:
        return '40,000 - 70,000'
    elif 'above ₹70,000' in val or '₹70,000  च्या वरती' in val or '70000 च्या वर' in val:
        return 'Above 70,000'
    else:
        return 'Other'


online_df['current_price_range'] = online_df['current_price_range'].apply(clean_online_price_range)

In [1413]:
online_df['current_price_range'].value_counts()

current_price_range
10,000 - 20,000    134
Below 10,000        64
20,000 - 40,000     38
Above 70,000        14
40,000 - 70,000      9
Name: count, dtype: int64

In [1414]:
manual_df['next_budget'].unique()

array([ 3.,  2.,  4.,  5.,  1., nan])

In [1415]:
manual_df['next_budget']= manual_df['next_budget'].map(maping_mannual_price_range)

In [1416]:
manual_df['next_budget'].value_counts()

next_budget
10,000 - 20,000    31
20,000 - 40,000    30
40,000 - 70,000    17
Below 10,000       13
Above 70,000        9
Name: count, dtype: int64

In [1417]:
online_df['next_budget'].unique()

array(['₹10,000 – ₹20,000', '₹20,000 – ₹40,000', 'Below 10,000',
       'Above ₹70,000', '₹40,000 – ₹70,000',
       'Below 10,000/ 10000 च्या खाली', 'Above ₹70,000/ 70000 च्या वर',
       nan], dtype=object)

In [1418]:
online_df['next_budget']= online_df['next_budget'].apply(clean_online_price_range)

In [1419]:
online_df['next_budget'].value_counts()

next_budget
20,000 - 40,000    95
10,000 - 20,000    68
Above 70,000       36
40,000 - 70,000    35
Below 10,000       20
Name: count, dtype: int64

In [1420]:
manual_df['usage_duration'].unique()

array([4, 2, 3, 1], dtype=int64)

In [1421]:
duration_map_manual = {
    1: 'Less than 6 months',
    2: '6 months - 1 year',
    3: '1 - 3 years',
    4: 'More than 3 years'
}

manual_df['usage_duration'] = manual_df['usage_duration'].map(duration_map_manual)

In [1422]:
manual_df['usage_duration'].value_counts()

usage_duration
1 - 3 years           38
More than 3 years     27
6 months - 1 year     23
Less than 6 months    13
Name: count, dtype: int64

In [1423]:
online_df['usage_duration'].unique()

array(['Less than 6 months', '6 months – 1 year', 'More than 2 years',
       'More than 3 years', '1 – 3 years',
       '6 months – 1 year/ 6 महिने - 1 वर्ष',
       'More than 3 years/ 3 वर्षांपेक्षा जास्त',
       'Less than 6 months/ 6 महिन्यांपेक्षा कमी',
       '1 – 3 years/ 1-3 वर्षे'], dtype=object)

In [1424]:
def clean_online_usage_duration(value):
    if pd.isna(value):
        return None
    value = value.strip().lower()
    
    if 'less than 6' in value or '6 महिन्यांपेक्षा कमी' in value:
        return 'Less than 6 months'
    elif '6 months' in value or '6 महिने' in value:
        return '6 months - 1 year'
    elif '1 – 3' in value or '1-3' in value or '1 – 3 years' in value or 'more than 2' in value:
        return '1 - 3 years'
    elif 'more than 3' in value or '3 वर्षांपेक्षा जास्त' in value:
        return 'More than 3 years'
    else:
        return 'Other'

In [1425]:
online_df['usage_duration'] = online_df['usage_duration'].apply(clean_online_usage_duration)

In [1426]:
print(online_df['usage_duration'].value_counts())

usage_duration
1 - 3 years           91
More than 3 years     85
6 months - 1 year     45
Less than 6 months    38
Name: count, dtype: int64

In [1427]:
manual_df['purchase_source'].unique()

array([1, 2, 3, 4, 5], dtype=int64)

In [1428]:
purchase_source_map_manual = {
    1: 'Online',
    2: 'Local Retail Store',
    3: 'Brand Outlet/Showroom',
    4: 'Second hand',
    5: 'Online'
}

manual_df['purchase_source'] = manual_df['purchase_source'].map(purchase_source_map_manual)

In [1429]:
manual_df['purchase_source'].value_counts()

purchase_source
Local Retail Store       35
Brand Outlet/Showroom    32
Online                   30
Second hand               4
Name: count, dtype: int64

In [1430]:
online_df['purchase_source'].unique()

array(['Online (Amazon, Flipkart, etc.)', 'Local Retail Store',
       'Brand Outlet/Showroom', 'Second hand',
       'Online (Amazon, Flipkart, etc.)/ ऑनलाइन (ऍमेझॉन, फ्लिपकार्ट इ.)',
       'Local Retail Store/ स्थानिक रिटेल स्टोअर',
       'Brand Outlet/Showroom/ ब्रँड आउटलेट/शोरूम',
       'Second hand / सेकंड हँड'], dtype=object)

In [1431]:
def clean_online_purchase_source(value):
    if pd.isna(value):
        return None
    value = value.strip().lower()
    
    if 'online' in value:
        return 'Online'
    elif 'retail' in value:
        return 'Local Retail Store'
    elif 'brand outlet' in value or 'showroom' in value:
        return 'Brand Outlet/Showroom'
    elif 'second hand' in value:
        return 'Second hand'
    else:
        return 'Other'

In [1432]:
online_df['purchase_source'] = online_df['purchase_source'].apply(clean_online_purchase_source)

In [1433]:
print(online_df['purchase_source'].value_counts())

purchase_source
Local Retail Store       146
Online                    51
Brand Outlet/Showroom     48
Second hand               14
Name: count, dtype: int64

In [1434]:
manual_df['purchase_preference'].unique()

array([ 1.,  2.,  3.,  4., nan])

In [1435]:
purchase_pref_map_manual = {
    1: 'Online',
    2: 'Offline (Retail Store)',
    3: 'Brand Showroom',
    4: 'Whichever gives the best deal'
}

manual_df['purchase_preference'] = manual_df['purchase_preference'].map(purchase_pref_map_manual)

In [1436]:
print(manual_df['purchase_preference'].value_counts(dropna=False))

purchase_preference
Offline (Retail Store)           37
Online                           27
Brand Showroom                   27
Whichever gives the best deal     9
NaN                               1
Name: count, dtype: int64

In [1437]:
online_df['purchase_preference'].unique()

array(['Ofline ( Retail store)', 'Whichever gives the best deal',
       'Online ( Amazon, Flipkart,etc)', 'Brand showroom/ store',
       'Ofline ( Retail store)/ ऑफलाईन (स्थानिक रिटेल स्टोअर)',
       'Whichever gives the best deal/ जे सर्वोत्तम डील देते',
       'Online( Amazon, Flipkart,etc)/ ऑनलाइन (ऍमेझॉन, फ्लिपकार्ट इ.)',
       'Brand showroom/ store/ ब्रँड आउटलेट/शोरूम'], dtype=object)

In [1438]:
def clean_online_purchase_preference(value):
    if pd.isna(value):
        return None
    val = value.strip().lower()
    
    if 'online' in val:
        return 'Online'
    elif 'ofline' in val or 'offline' in val or 'retail' in val:
        return 'Offline (Retail Store)'
    elif 'brand showroom' in val or 'brand outlet' in val:
        return 'Brand Showroom'
    elif 'deal' in val:
        return 'Whichever gives the best deal'
    else:
        return 'Other'

In [1439]:
online_df['purchase_preference'] = online_df['purchase_preference'].apply(clean_online_purchase_preference)

In [1440]:
print(online_df['purchase_preference'].value_counts(dropna=False))

purchase_preference
Offline (Retail Store)           127
Brand Showroom                    51
Online                            49
Whichever gives the best deal     32
Name: count, dtype: int64

In [1441]:
manual_df['upgrade_frequency'].unique()

array([4, 3, 2, 1], dtype=int64)

In [1442]:
upgrade_map_manual = {
    1: 'Every year',
    2: 'Every 2 years',
    3: 'Every 3+ years',
    4: 'Only when my phone stops working'
}

manual_df['upgrade_frequency'] = manual_df['upgrade_frequency'].map(upgrade_map_manual)

In [1443]:
print(manual_df['upgrade_frequency'].value_counts(dropna=False))

upgrade_frequency
Only when my phone stops working    44
Every 3+ years                      25
Every 2 years                       20
Every year                          12
Name: count, dtype: int64

In [1444]:
online_df['upgrade_frequency'].unique()

array(['Every 2 years', 'Only when my phone stops working', 'Every year',
       'Every 3+ years',
       'Only when my phone stops working/ जेव्हा माझा फोन काम करणे थांबवतो तेव्हाच',
       'Every year/ दर वर्षी', 'Every 3+ years/ दर तीन वर्षांनी',
       'Every 2 years/ दर दोन वर्षांनी'], dtype=object)

In [1445]:
def clean_online_upgrade_frequency(value):
    if pd.isna(value):
        return None
    val = value.strip().lower()

    if 'every year' in val:
        return 'Every year'
    elif 'every 2 years' in val:
        return 'Every 2 years'
    elif 'every 3' in val:
        return 'Every 3+ years'
    elif 'only when' in val or 'फोन काम करणे थांबवतो' in val:
        return 'Only when my phone stops working'
    else:
        return 'Other'

In [1446]:
online_df['upgrade_frequency'] = online_df['upgrade_frequency'].apply(clean_online_upgrade_frequency)

In [1447]:
print(online_df['upgrade_frequency'].value_counts(dropna=False))

upgrade_frequency
Only when my phone stops working    160
Every 3+ years                       40
Every year                           35
Every 2 years                        24
Name: count, dtype: int64

In [1448]:
manual_df['resale_consideration'].unique()

array([ 2.,  1.,  3.,  4., nan])

In [1449]:
map_resale_consideration = {
    1: 'Yes',
    2: 'No',
    3: 'No',
    4: 'No'
}

manual_df['resale_consideration']= manual_df['resale_consideration'].map(map_resale_consideration)

In [1450]:
manual_df['resale_consideration'].value_counts()

resale_consideration
No     69
Yes    31
Name: count, dtype: int64

In [1451]:
online_df['resale_consideration'].unique()

array(['Yes', 'No', 'Yes/ हो', 'No/ नाही'], dtype=object)

In [1452]:
def clean_yes_no_response(value):
    if pd.isna(value):
        return None
    val = value.strip().lower()

    if 'yes' in val or 'yes/ हो' in val:
        return 'Yes'
    elif 'no' in val or 'no/ नाही':
        return 'No'
    else:
        return 'Other'

In [1453]:
online_df['resale_consideration'] = online_df['resale_consideration'].apply(clean_yes_no_response)

In [1454]:
online_df['resale_consideration'].value_counts()

resale_consideration
Yes    134
No     125
Name: count, dtype: int64

In [1455]:
manual_df['satisfaction'].unique()

array(['yes', 2, 1, 'No', 'Yes', 'no', nan], dtype=object)

In [1456]:
manual_df['satisfaction']= manual_raw['Are you satisfied with your current smartphone']

In [1457]:
map_satisfaction = {
    1: 'Yes',
    2: 'No',
    'yes': 'Yes',
    'no': 'No'
}

manual_df['satisfaction']  = manual_df['satisfaction'].map(map_satisfaction)

In [1458]:
manual_df['satisfaction'].value_counts()

satisfaction
Yes    59
No     13
Name: count, dtype: int64

In [1459]:
online_df['satisfaction'].unique()

array(['Yes', 'No', 'Yes/ होय', 'No/ नाही'], dtype=object)

In [1460]:
online_df['satisfaction']= online_df['satisfaction'].apply(clean_yes_no_response)

In [1461]:
online_df['satisfaction'].value_counts()

satisfaction
Yes    220
No      39
Name: count, dtype: int64

In [1462]:
manual_df['foldable_interest'].unique()

array([ 2.,  3.,  1., nan])

In [1463]:
map_foldable_interest = {
    1: 'Yes',
    2:'No',
    3:'Maybe'
}

manual_df['foldable_interest']= manual_df['foldable_interest'].map(map_foldable_interest)

In [1464]:
manual_df['foldable_interest'].value_counts()

foldable_interest
Maybe    36
No       34
Yes      30
Name: count, dtype: int64

In [1465]:
online_df['foldable_interest'].unique()

array(['Maybe', 'No', 'Yes', nan, 'Yes/ हो', 'Maybe/ कदाचित', 'No/ नाही'],
      dtype=object)

In [1466]:
def clean_foldable_interest(value):
    if pd.isna(value):
        return None
    val = value.strip().lower()

    if 'yes' in val or 'हो' in val:
        return 'Yes'
    elif 'no' in val or 'नाही' in val:
        return 'No'
    elif 'maybe' in val or 'कदाचित' in val:
        return 'Maybe'
    else:
        return 'Other'

In [1467]:
online_df['foldable_interest'] = online_df['foldable_interest'].apply(clean_foldable_interest)

In [1468]:
online_df['foldable_interest'].value_counts()

foldable_interest
Yes      96
Maybe    86
No       68
Name: count, dtype: int64

In [1469]:
manual_df['indian_brand_preference'].unique()

array([ 1.,  3.,  2., nan])

In [1470]:
map_indian_brd_pref = {
    1:'Yes',
    2:'No',
    3:"Doesn't matter"
}

manual_df['indian_brand_preference']= manual_df['indian_brand_preference'].map(map_indian_brd_pref)

In [1471]:
manual_df['indian_brand_preference'].value_counts()

indian_brand_preference
No                37
Yes               32
Doesn't matter    31
Name: count, dtype: int64

In [1472]:
online_df['indian_brand_preference'].unique()

array(["Doesn't matter", 'Yes', nan, 'No', 'Yes/ हो',
       "Doesn't matter/ फरक पडत नाही", 'No/ नाही'], dtype=object)

In [1473]:
def clean_ind_brd_pref(value):
    if pd.isna(value):
        return None
    val = value.strip().lower()

    if 'yes' in val or 'हो' in val:
        return 'Yes'
    elif 'no' in val or 'नाही' in val:
        return 'No'
    elif "doesn't matter" in val or 'फरक पडत नाही' in val:
        return "Doesn't matter"
    else:
        return 'Other'

In [1474]:
online_df['indian_brand_preference'] =online_df['indian_brand_preference'].apply(clean_ind_brd_pref)

In [1475]:
online_df['indian_brand_preference'].value_counts()

indian_brand_preference
Yes               142
No                 84
Doesn't matter     23
Name: count, dtype: int64

In [1476]:
manual_df['most_used_feature'].unique()

array([ 6,  1,  2,  7,  4,  3,  5,  8,  9, 10], dtype=int64)

In [1477]:
map_most_used_feature = {
    1:'Communication',
    2:'Social media',
    3:'Web browsing ',
    4:'Camera',
    5:'Gaming',
    6:'Office works',
    7:'Other',
    8:'Communication',
    9:'Social media',
    10:'Camera'
}

In [1478]:
manual_df['most_used_feature'] = manual_df['most_used_feature'].map(map_most_used_feature)

In [1479]:
manual_df['most_used_feature'].value_counts()

most_used_feature
Social media     46
Communication    18
Web browsing     13
Camera            9
Office works      8
Other             5
Gaming            2
Name: count, dtype: int64

In [1480]:
online_df['most_used_feature'].unique()

array(['Web browsing', 'Social media', 'Other', 'Communication',
       'Office works', 'Camera', 'Gaming', 'Communication/ संवाद',
       'Other/ इतर', 'Social media/ सोशल मेडिया', 'Gaming/ गेमिंग',
       'Web browsing/ वेब ब्राउझिंग', 'Office works/  कर्यालयीन कामे',
       'Camera/ कॅमेरा'], dtype=object)

In [1481]:
def clean_most_used_feature(value):
    if pd.isna(value):
        return None
    val = value.strip().lower()
    
    if 'web' in val:
        return 'Web browsing'
    elif 'social' in val:
        return 'Social media'
    elif 'communication' in val or 'संवाद' in val:
        return 'Communication'
    elif 'office' in val or 'कार्यालयीन' in val:
        return 'Office works'
    elif 'camera' in val or 'कॅमेरा' in val:
        return 'Camera'
    elif 'gaming' in val or 'गेमिंग' in val:
        return 'Gaming'
    elif 'other' in val or 'इतर' in val:
        return 'Other'
    else:
        return 'Other'

In [1482]:
online_df['most_used_feature'] = online_df['most_used_feature'].apply(clean_most_used_feature)

In [1483]:
print(online_df['most_used_feature'].value_counts(dropna=False))

most_used_feature
Social media     80
Communication    71
Other            29
Web browsing     25
Office works     21
Camera           19
Gaming           14
Name: count, dtype: int64

In [1484]:
manual_df['next_brand_preference'].unique()

array(['SamsunggS25', 'vivo 20s', 'oneplus', 'sumsung galaxy', 'oppo y22',
       'iphone', 'vivo 22a', 'poco c61', 'sumsung y33', 'Apple', 'apple',
       'Samsung', 'realme', 'samsung', 'samsungs25', 'oppo  A77',
       'Samsung A35 5G', 'vivo y16', 'oppo A27', 'motorola',
       'sumsung s24', 'vivo A66', 'oppo', 'Samsung S25', 'Apple 16',
       'IQOO 13', 'Vivo ', 'Vivo', 'Xiomi', 'Lava', 'samsung Galaxy',
       'redmi', 'one plus', 'poco', 'iphone 16', 'vivo', 'iphone16 plus',
       'google pixel', 'samsung S25', nan], dtype=object)

In [1485]:
def clean_next_brand_preference(value):
    if pd.isna(value):
        return None
    val = str(value).strip().lower()

    if any(x in val for x in ['apple', 'iphone', 'i phone', 'iphon']):
        return 'Apple'
    elif any(x in val for x in ['samsung', 'samang', 'samsang', 'samangalxy', 'samsun']):
        return 'Samsung'
    elif any(x in val for x in ['vivo']):
        return 'Vivo'
    elif any(x in val for x in ['oppo']):
        return 'Oppo'
    elif any(x in val for x in ['realme', 'realmi', 'relame']):
        return 'Realme'
    elif any(x in val for x in ['redmi', 'xiomi', 'mi']):
        return 'Redmi'
    elif any(x in val for x in ['oneplus', '1 plus', 'one plus']):
        return 'OnePlus'
    elif any(x in val for x in ['motorola', 'moto']):
        return 'Motorola'
    elif any(x in val for x in ['poco']):
        return 'Poco'
    elif any(x in val for x in ['iqoo']):
        return 'iQOO'
    elif any(x in val for x in ['nothing']):
        return 'Nothing'
    elif any(x in val for x in ['google', 'pixel']):
        return 'Google'
    elif any(x in val for x in ['lava']):
        return 'Lava'
    elif any(x in val for x in ['nokia']):
        return 'Nokia'
    elif val in ['no', 'nahi', 'ok', "i don't know", 'best experience', 'more features']:
        return 'Unknown'
    else:
        return 'Unknown'

In [1486]:
manual_df['next_brand_preference']=manual_df['next_brand_preference'].apply(clean_next_brand_preference)

In [1487]:
manual_df['next_brand_preference'].value_counts(dropna=False)

next_brand_preference
Apple       29
Samsung     17
Vivo        14
OnePlus     10
Oppo         5
Realme       4
Lava         4
Google       4
Unknown      3
Poco         3
Motorola     3
Redmi        3
iQOO         1
None         1
Name: count, dtype: int64

In [1488]:
online_df['next_brand_preference'].unique()

array(['Oppo ', 'No', 'One plus ', 'Yes', 'Realme ', 'Samsung ',
       'Motorola ', '1 plus ', 'Samsung', 'Reamle ', 'OnePlus ',
       'IPhone ', 'iPhone ', 'I phone ', 'I phone pro max', 'Iphone',
       'Apple ', 'Only vivo', 'One Plus ', 'Sumsung S 24 ultra ',
       'Google pixel', 'Vivo', 'vivo ', 'Samsung or vivo ', 'Samsung S25',
       'Apple', 'Iphone 18', 'Oppo k12x ', 'Poco m5', 'Redmi 14 pro 5g',
       'Samsung S series or iphone', 'Redmi',
       'Not sure but redmi or realme', 'Best experience ', 'iPhones',
       'One plus', 'नो', 'Nahi', 'Realme , apple', 'Oneplus',
       'Samsung S24', 'I phone 14 pro max ', "Samsung's S23",
       'I phone 15 pro', 'Oppo', 'Samsung S24 Ultra ', ' Samsung',
       'Nothing ', 'Google ', 'IPhone', 'Samang ultra plus',
       'More features  ', 'Iphon ', 'Realme 5G', 'iPhone 15', 'Appel ',
       'Samsang latest model', 'Realme', 'Oppo,vivo, samsung',
       'iPhone 17 pro max', "Nooo my phone is best' ", 'Oneplus ',
       'iPhone 15 ', 'oppo N1 ', 'Redmi note 9', 'Samsang gelasi s25',
       'iPhone 17 ', 'iPhone 17 pro', "Samsung's", 'Iphone ',
       'Vivo V15 pro', 'vivo', 'Oppo 17s 5G', 'Vivo ', 'Vivo C61',
       'OPPO 17s', 'Poco', 'Vivo c17', 'OnePlus nord CE 5G',
       'I phone 16 ', 'One plus nord CE 5G ', 'Vivo y25', 'Relame ',
       'Samangalxy s20', 'Samsung galaxy s20 ultra plus ', 'SAMSANG',
       'Samsung Galaxy', 'Vivo Y300', 'motorola', 'Realme or redmi ',
       'I phone', 'Ok', 'iphone ', 'Iqoo', nan, 'Vivo y53', 'Poco ',
       'Realmi ', 'Motorola', 'Realmi note pro', 'Vivo m22', 'Vivo y16',
       'Samsung m31', 'Lava ', 'Samsun', 'Geiie', 'Samsung s25',
       'iPhone 16', 'Oppo A77 ', 'Samsung galaxy s24 ultra',
       "I don't know ", 'iPhone 14', 'Samsung galaxy ', 'Realme 12x ',
       'i phone ', 'Samsung, IQOO', 'samsung galaxy edge',
       'IQOO, Samsung', 'Samsung smart phone ', 'Samsung galaxy note ',
       'Nokia ', 'Samsung galaxy 24 ultra Pro max',
       'Oppo, nothing Onepls ', 'Samsung galaxy 24 ultra Pro max ',
       'Iphone 16 pro max', 'iPhone', 'Xiomi', 'Vivo V50 Pro', 'OPPO N1 '],
      dtype=object)

In [1489]:
online_df['next_brand_preference'] = online_df['next_brand_preference'].apply(clean_next_brand_preference)

In [1490]:
print(online_df['next_brand_preference'].value_counts(dropna=False))

next_brand_preference
Apple       73
Samsung     63
Vivo        30
OnePlus     20
Unknown     19
Oppo        15
Realme      14
Redmi        7
Motorola     5
Google       4
Poco         4
Nothing      1
iQOO         1
None         1
Lava         1
Nokia        1
Name: count, dtype: int64

In [1491]:
manual_df['top_3_reasons'].unique()

array(['1,5,6', '2,3,9', '1,2,8', '4,5,8', '1,2,3', '2,3,4', '5,9,10',
       '2,9,10', '4,6,8', '1,3,5', '2,4,5', '2,5,9', '1,4,5', '1,4,7',
       '2,3,6', '1,2,4', '1,5,8', '1,4,9', '2,3,5', '1,4,6', '2,4,6',
       '2,8,10', '1,8,9', '4,5,9', '1,5.9', '3,4,5', '1,2,5', '2,3,7',
       '3,5,6', '1,3,4', '3,4', '1,3,4,5', '2,3,4,5', '2,7,8', '1,7,6',
       '2,5,6', '1,5,5', '4,5,1', '2,7,6', '1,5,3', '5,6,1', '4,2,5',
       '5,7,9', '5,6,7', '5,4,1', '7,8,9', '3,7,9', '3,8,9', '2;5;6',
       '4,7,9'], dtype=object)

In [1492]:
reason_map = {
    '1': 'Camera quality',
    '2': 'Battery life',
    '3': 'Processor performance',
    '4': 'Display quality',
    '5': 'Storage & RAM',
    '6': 'Price & affordability',
    '7': 'Brand reputation',
    '8': '5G support',
    '9': 'Software & UI Experience',
    '10': 'After-Sales Service'
}

In [1493]:
def map_manual_reasons(code_str):
    if pd.isna(code_str):
        return None

    # Replace separators if any are incorrect (e.g., semicolon)
    code_str = code_str.replace(';', ',')
    
    codes = [c.strip() for c in code_str.split(',')]

    mapped = [reason_map.get(code, f"Unknown-{code}") for code in codes if code]
    return ', '.join(mapped)

In [1494]:
manual_df['top_3_reasons'] = manual_df['top_3_reasons'].apply(map_manual_reasons)

In [1495]:
manual_df['top_3_reasons'].unique()

array(['Camera quality, Storage & RAM, Price & affordability',
       'Battery life, Processor performance, Software & UI Experience',
       'Camera quality, Battery life, 5G support',
       'Display quality, Storage & RAM, 5G support',
       'Camera quality, Battery life, Processor performance',
       'Battery life, Processor performance, Display quality',
       'Storage & RAM, Software & UI Experience, After-Sales Service',
       'Battery life, Software & UI Experience, After-Sales Service',
       'Display quality, Price & affordability, 5G support',
       'Camera quality, Processor performance, Storage & RAM',
       'Battery life, Display quality, Storage & RAM',
       'Battery life, Storage & RAM, Software & UI Experience',
       'Camera quality, Display quality, Storage & RAM',
       'Camera quality, Display quality, Brand reputation',
       'Battery life, Processor performance, Price & affordability',
       'Camera quality, Battery life, Display quality',
       'Camera quality, Storage & RAM, 5G support',
       'Camera quality, Display quality, Software & UI Experience',
       'Battery life, Processor performance, Storage & RAM',
       'Camera quality, Display quality, Price & affordability',
       'Battery life, Display quality, Price & affordability',
       'Battery life, 5G support, After-Sales Service',
       'Camera quality, 5G support, Software & UI Experience',
       'Display quality, Storage & RAM, Software & UI Experience',
       'Camera quality, Unknown-5.9',
       'Processor performance, Display quality, Storage & RAM',
       'Camera quality, Battery life, Storage & RAM',
       'Battery life, Processor performance, Brand reputation',
       'Processor performance, Storage & RAM, Price & affordability',
       'Camera quality, Processor performance, Display quality',
       'Processor performance, Display quality',
       'Camera quality, Processor performance, Display quality, Storage & RAM',
       'Battery life, Processor performance, Display quality, Storage & RAM',
       'Battery life, Brand reputation, 5G support',
       'Camera quality, Brand reputation, Price & affordability',
       'Battery life, Storage & RAM, Price & affordability',
       'Camera quality, Storage & RAM, Storage & RAM',
       'Display quality, Storage & RAM, Camera quality',
       'Battery life, Brand reputation, Price & affordability',
       'Camera quality, Storage & RAM, Processor performance',
       'Storage & RAM, Price & affordability, Camera quality',
       'Display quality, Battery life, Storage & RAM',
       'Storage & RAM, Brand reputation, Software & UI Experience',
       'Storage & RAM, Price & affordability, Brand reputation',
       'Storage & RAM, Display quality, Camera quality',
       'Brand reputation, 5G support, Software & UI Experience',
       'Processor performance, Brand reputation, Software & UI Experience',
       'Processor performance, 5G support, Software & UI Experience',
       'Display quality, Brand reputation, Software & UI Experience'],
      dtype=object)

In [1496]:
online_df['top_3_reasons'].unique()

array(['Camera quality, Processor performance, Display quality, Price & affordability, Brand reputation, 5G support',
       'Camera quality, Battery life, Processor performance, Display quality, Storage & RAM, Price & affordability, Brand reputation, 5G support, Software & UI Experience, After-Sales Service',
       'Camera quality, Storage & RAM, Brand reputation',
       'After-Sales Service',
       'Camera quality, Storage & RAM, Price & affordability',
       'Camera quality, Price & affordability, 5G support',
       'Camera quality, Battery life, Processor performance, Brand reputation, 5G support',
       'Camera quality, Battery life, Processor performance, Display quality, Storage & RAM, Price & affordability, Brand reputation',
       'Camera quality, Storage & RAM, 5G support',
       'Camera quality, Price & affordability, Brand reputation',
       'Camera quality, Battery life, Processor performance, Display quality, Storage & RAM, 5G support, Software & UI Experience',
       'Camera quality, Display quality, Storage & RAM',
       'Camera quality, Battery life, Display quality, Price & affordability',
       'Battery life, Display quality, Storage & RAM',
       'Camera quality, Processor performance, Storage & RAM',
       'Camera quality, Battery life, Storage & RAM, 5G support',
       'Camera quality, Battery life, Storage & RAM',
       'Battery life, Display quality, 5G support',
       'Battery life, Brand reputation, After-Sales Service',
       'Camera quality, Battery life, Processor performance, Display quality, Storage & RAM, Price & affordability',
       '5G support', 'Battery life, Storage & RAM, Brand reputation',
       'Battery life', 'Processor performance, Storage & RAM, 5G support',
       'Camera quality, Processor performance, Display quality, Storage & RAM, Brand reputation, 5G support, After-Sales Service',
       'Battery life, Processor performance, Display quality, Storage & RAM, Price & affordability, Brand reputation, 5G support',
       'Camera quality, Battery life, Display quality',
       'Battery life, Processor performance, Storage & RAM',
       'Camera quality, Battery life, Processor performance',
       'Camera quality, Processor performance, Display quality, Storage & RAM, Price & affordability, Brand reputation',
       'Camera quality, Battery life, Storage & RAM, Price & affordability, 5G support',
       'Storage & RAM',
       'Camera quality, Processor performance, Display quality, Storage & RAM, Brand reputation',
       'Camera quality, Battery life, 5G support',
       'Battery life, Processor performance, Display quality, Storage & RAM, Price & affordability, 5G support, Software & UI Experience',
       'Price & affordability',
       'Camera quality, Battery life, Processor performance, Display quality, Storage & RAM, Brand reputation, 5G support',
       'Camera quality, Battery life, Storage & RAM, Price & affordability, 5G support, Software & UI Experience',
       'Camera quality, Processor performance, Software & UI Experience',
       'Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता',
       '5G support/ 5G सपोर्ट',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी, Brand reputation/ ब्रँड प्रतिष्ठा, After-Sales Service/ विक्रीनंतरची सेवा',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Price & affordability/ किंमत आणि परवडणारी क्षमता',
       'Camera quality/ कॅमेरा गुणवत्ता',
       'Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता, 5G support/ 5G सपोर्ट',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता, Brand reputation/ ब्रँड प्रतिष्ठा, After-Sales Service/ विक्रीनंतरची सेवा',
       'Camera quality/ कॅमेरा गुणवत्ता, Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता',
       'Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता, Brand reputation/ ब्रँड प्रतिष्ठा, 5G support/ 5G सपोर्ट, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM',
       'Battery life/ बॅटरी आयुष्य, Display quality/  डिस्प्ले क्वालिटी, Brand reputation/ ब्रँड प्रतिष्ठा',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM',
       'Storage & RAM / स्टोरेज & RAM',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, 5G support/ 5G सपोर्ट',
       'Camera quality/ कॅमेरा गुणवत्ता, Display quality/  डिस्प्ले क्वालिटी, 5G support/ 5G सपोर्ट',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Storage & RAM / स्टोरेज & RAM',
       'Price & affordability/ किंमत आणि परवडणारी क्षमता',
       'Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, 5G support/ 5G सपोर्ट',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर',
       'Camera quality/ कॅमेरा गुणवत्ता, Processor performance/ प्रोसेसर, 5G support/ 5G सपोर्ट',
       'Camera quality/ कॅमेरा गुणवत्ता, 5G support/ 5G सपोर्ट, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Camera quality/ कॅमेरा गुणवत्ता, Storage & RAM / स्टोरेज & RAM, 5G support/ 5G सपोर्ट',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी, 5G support/ 5G सपोर्ट',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Display quality/  डिस्प्ले क्वालिटी',
       'Camera quality/ कॅमेरा गुणवत्ता, Display quality/  डिस्प्ले क्वालिटी, Brand reputation/ ब्रँड प्रतिष्ठा',
       'Display quality/  डिस्प्ले क्वालिटी, Price & affordability/ किंमत आणि परवडणारी क्षमता, 5G support/ 5G सपोर्ट',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता, Brand reputation/ ब्रँड प्रतिष्ठा, 5G support/ 5G सपोर्ट, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव, After-Sales Service/ विक्रीनंतरची सेवा',
       'Processor performance/ प्रोसेसर, Brand reputation/ ब्रँड प्रतिष्ठा, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM',
       'Processor performance/ प्रोसेसर, Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता',
       'Battery life/ बॅटरी आयुष्य, Display quality/  डिस्प्ले क्वालिटी, 5G support/ 5G सपोर्ट',
       'Processor performance/ प्रोसेसर, Storage & RAM / स्टोरेज & RAM, 5G support/ 5G सपोर्ट',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता',
       'Battery life/ बॅटरी आयुष्य, Price & affordability/ किंमत आणि परवडणारी क्षमता, After-Sales Service/ विक्रीनंतरची सेवा',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता, Brand reputation/ ब्रँड प्रतिष्ठा, 5G support/ 5G सपोर्ट, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Brand reputation/ ब्रँड प्रतिष्ठा',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM, 5G support/ 5G सपोर्ट, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव, After-Sales Service/ विक्रीनंतरची सेवा',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी',
       'Battery life/ बॅटरी आयुष्य, Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य',
       'Processor performance/ प्रोसेसर',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता, Brand reputation/ ब्रँड प्रतिष्ठा',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता, Brand reputation/ ब्रँड प्रतिष्ठा, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Camera quality/ कॅमेरा गुणवत्ता, Display quality/  डिस्प्ले क्वालिटी, Brand reputation/ ब्रँड प्रतिष्ठा, 5G support/ 5G सपोर्ट, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Battery life/ बॅटरी आयुष्य, Price & affordability/ किंमत आणि परवडणारी क्षमता, 5G support/ 5G सपोर्ट',
       'Battery life/ बॅटरी आयुष्य, 5G support/ 5G सपोर्ट, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Battery life/ बॅटरी आयुष्य, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM, Brand reputation/ ब्रँड प्रतिष्ठा',
       'Camera quality/ कॅमेरा गुणवत्ता, Processor performance/ प्रोसेसर, Storage & RAM / स्टोरेज & RAM, Brand reputation/ ब्रँड प्रतिष्ठा, 5G support/ 5G सपोर्ट, After-Sales Service/ विक्रीनंतरची सेवा',
       'Battery life/ बॅटरी आयुष्य, Display quality/  डिस्प्ले क्वालिटी, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Camera quality/ कॅमेरा गुणवत्ता, Display quality/  डिस्प्ले क्वालिटी',
       'Camera quality/ कॅमेरा गुणवत्ता, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी, Brand reputation/ ब्रँड प्रतिष्ठा',
       'Camera quality/ कॅमेरा गुणवत्ता, Processor performance/ प्रोसेसर, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM, 5G support/ 5G सपोर्ट, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Processor performance/ प्रोसेसर, Price & affordability/ किंमत आणि परवडणारी क्षमता, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Battery life/ बॅटरी आयुष्य, Storage & RAM / स्टोरेज & RAM, 5G support/ 5G सपोर्ट',
       'Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM, 5G support/ 5G सपोर्ट',
       'Battery life/ बॅटरी आयुष्य, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM',
       'Camera quality/ कॅमेरा गुणवत्ता, Processor performance/ प्रोसेसर, Storage & RAM / स्टोरेज & RAM',
       'Camera quality/ कॅमेरा गुणवत्ता, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी',
       'Camera quality/ कॅमेरा गुणवत्ता, Processor performance/ प्रोसेसर, Price & affordability/ किंमत आणि परवडणारी क्षमता',
       'Camera quality/ कॅमेरा गुणवत्ता, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM',
       'Battery life/ बॅटरी आयुष्य',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Display quality/  डिस्प्ले क्वालिटी, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Storage & RAM / स्टोरेज & RAM',
       'Battery life/ बॅटरी आयुष्य, Price & affordability/ किंमत आणि परवडणारी क्षमता, Brand reputation/ ब्रँड प्रतिष्ठा',
       'Battery life/ बॅटरी आयुष्य, Display quality/  डिस्प्ले क्वालिटी, Price & affordability/ किंमत आणि परवडणारी क्षमता',
       'Camera quality/ कॅमेरा गुणवत्ता, Processor performance/ प्रोसेसर, Brand reputation/ ब्रँड प्रतिष्ठा, 5G support/ 5G सपोर्ट, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव, After-Sales Service/ विक्रीनंतरची सेवा',
       'Camera quality/ कॅमेरा गुणवत्ता, Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता, 5G support/ 5G सपोर्ट',
       'Battery life/ बॅटरी आयुष्य, Storage & RAM / स्टोरेज & RAM, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM, Brand reputation/ ब्रँड प्रतिष्ठा, 5G support/ 5G सपोर्ट, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Storage & RAM / स्टोरेज & RAM, Brand reputation/ ब्रँड प्रतिष्ठा, 5G support/ 5G सपोर्ट, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       '5G support/ 5G सपोर्ट, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव, After-Sales Service/ विक्रीनंतरची सेवा',
       'Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी',
       'Price & affordability/ किंमत आणि परवडणारी क्षमता, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव, After-Sales Service/ विक्रीनंतरची सेवा',
       'Camera quality/ कॅमेरा गुणवत्ता, Brand reputation/ ब्रँड प्रतिष्ठा, After-Sales Service/ विक्रीनंतरची सेवा',
       'Camera quality/ कॅमेरा गुणवत्ता, Processor performance/ प्रोसेसर, Storage & RAM / स्टोरेज & RAM, Brand reputation/ ब्रँड प्रतिष्ठा, 5G support/ 5G सपोर्ट, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Processor performance/ प्रोसेसर, Price & affordability/ किंमत आणि परवडणारी क्षमता, After-Sales Service/ विक्रीनंतरची सेवा',
       'Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Storage & RAM / स्टोरेज & RAM, 5G support/ 5G सपोर्ट, After-Sales Service/ विक्रीनंतरची सेवा',
       'Camera quality/ कॅमेरा गुणवत्ता, Price & affordability/ किंमत आणि परवडणारी क्षमता, 5G support/ 5G सपोर्ट',
       'Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Price & affordability/ किंमत आणि परवडणारी क्षमता, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Display quality/  डिस्प्ले क्वालिटी',
       'Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता, 5G support/ 5G सपोर्ट',
       'Camera quality/ कॅमेरा गुणवत्ता, Storage & RAM / स्टोरेज & RAM, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव, After-Sales Service/ विक्रीनंतरची सेवा',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Storage & RAM / स्टोरेज & RAM, 5G support/ 5G सपोर्ट',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता, Brand reputation/ ब्रँड प्रतिष्ठा, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव, After-Sales Service/ विक्रीनंतरची सेवा',
       'Camera quality/ कॅमेरा गुणवत्ता, Storage & RAM / स्टोरेज & RAM, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Camera quality/ कॅमेरा गुणवत्ता, Processor performance/ प्रोसेसर, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM, Brand reputation/ ब्रँड प्रतिष्ठा, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Camera quality/ कॅमेरा गुणवत्ता, Display quality/  डिस्प्ले क्वालिटी, Price & affordability/ किंमत आणि परवडणारी क्षमता, Brand reputation/ ब्रँड प्रतिष्ठा, 5G support/ 5G सपोर्ट, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Camera quality/ कॅमेरा गुणवत्ता, Display quality/  डिस्प्ले क्वालिटी, Price & affordability/ किंमत आणि परवडणारी क्षमता',
       'Battery life/ बॅटरी आयुष्य, Storage & RAM / स्टोरेज & RAM, After-Sales Service/ विक्रीनंतरची सेवा',
       'Camera quality/ कॅमेरा गुणवत्ता, Display quality/  डिस्प्ले क्वालिटी, Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता, 5G support/ 5G सपोर्ट',
       'Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Price & affordability/ किंमत आणि परवडणारी क्षमता, 5G support/ 5G सपोर्ट',
       'Display quality/  डिस्प्ले क्वालिटी, Brand reputation/ ब्रँड प्रतिष्ठा, Software & UI Experience/ सॉफ्टवेअर आणि UI अनुभव',
       'Camera quality/ कॅमेरा गुणवत्ता, Battery life/ बॅटरी आयुष्य, Processor performance/ प्रोसेसर, Storage & RAM / स्टोरेज & RAM, Price & affordability/ किंमत आणि परवडणारी क्षमता'],
      dtype=object)

In [1497]:
def clean_reasons(text):
    if pd.isna(text):
        return None

    text = text.lower()

    cleaned = []

    if 'camera' in text or 'कॅमेरा' in text:
        cleaned.append('Camera quality')
    if 'battery' in text or 'बॅटरी' in text:
        cleaned.append('Battery life')
    if 'processor' in text or 'प्रोसेसर' in text:
        cleaned.append('Processor performance')
    if 'display' in text or 'डिस्प्ले' in text:
        cleaned.append('Display quality')
    if 'storage' in text or 'ram' in text or 'स्टोरेज' in text:
        cleaned.append('Storage & RAM')
    if 'price' in text or 'affordability' in text or 'किंमत' in text:
        cleaned.append('Price & affordability')
    if 'brand' in text or 'ब्रँड' in text:
        cleaned.append('Brand reputation')
    if '5g' in text:
        cleaned.append('5G support')
    if 'software' in text or 'ui' in text:
        cleaned.append('Software & UI Experience')
    if 'after-sales' in text or 'service' in text or 'विक्रीनंतर' in text:
        cleaned.append('After-Sales Service')

    return ', '.join(cleaned)

In [1498]:
online_df['top_3_reasons'] = online_df['top_3_reasons'].apply(clean_reasons)

In [1499]:
online_df['top_3_reasons'].unique()

array(['Camera quality, Processor performance, Display quality, Price & affordability, Brand reputation, 5G support',
       'Camera quality, Battery life, Processor performance, Display quality, Storage & RAM, Price & affordability, Brand reputation, 5G support, Software & UI Experience, After-Sales Service',
       'Camera quality, Storage & RAM, Brand reputation',
       'After-Sales Service',
       'Camera quality, Storage & RAM, Price & affordability',
       'Camera quality, Price & affordability, 5G support',
       'Camera quality, Battery life, Processor performance, Brand reputation, 5G support',
       'Camera quality, Battery life, Processor performance, Display quality, Storage & RAM, Price & affordability, Brand reputation',
       'Camera quality, Storage & RAM, 5G support',
       'Camera quality, Price & affordability, Brand reputation',
       'Camera quality, Battery life, Processor performance, Display quality, Storage & RAM, 5G support, Software & UI Experience',
       'Camera quality, Display quality, Storage & RAM',
       'Camera quality, Battery life, Display quality, Price & affordability',
       'Battery life, Display quality, Storage & RAM',
       'Camera quality, Processor performance, Storage & RAM',
       'Camera quality, Battery life, Storage & RAM, 5G support',
       'Camera quality, Battery life, Storage & RAM',
       'Battery life, Display quality, 5G support',
       'Battery life, Brand reputation, After-Sales Service',
       'Camera quality, Battery life, Processor performance, Display quality, Storage & RAM, Price & affordability',
       '5G support', 'Battery life, Storage & RAM, Brand reputation',
       'Battery life', 'Processor performance, Storage & RAM, 5G support',
       'Camera quality, Processor performance, Display quality, Storage & RAM, Brand reputation, 5G support, After-Sales Service',
       'Battery life, Processor performance, Display quality, Storage & RAM, Price & affordability, Brand reputation, 5G support',
       'Camera quality, Battery life, Display quality',
       'Battery life, Processor performance, Storage & RAM',
       'Camera quality, Battery life, Processor performance',
       'Camera quality, Processor performance, Display quality, Storage & RAM, Price & affordability, Brand reputation',
       'Camera quality, Battery life, Storage & RAM, Price & affordability, 5G support',
       'Storage & RAM',
       'Camera quality, Processor performance, Display quality, Storage & RAM, Brand reputation',
       'Camera quality, Battery life, 5G support',
       'Battery life, Processor performance, Display quality, Storage & RAM, Price & affordability, 5G support, Software & UI Experience',
       'Price & affordability',
       'Camera quality, Battery life, Processor performance, Display quality, Storage & RAM, Brand reputation, 5G support',
       'Camera quality, Battery life, Storage & RAM, Price & affordability, 5G support, Software & UI Experience',
       'Camera quality, Processor performance, Software & UI Experience',
       'Battery life, Processor performance, Storage & RAM, Price & affordability',
       'Camera quality, Battery life, Processor performance, Display quality, Brand reputation, After-Sales Service',
       'Camera quality, Battery life, Price & affordability',
       'Camera quality',
       'Storage & RAM, Price & affordability, 5G support',
       'Camera quality, Battery life, Processor performance, Display quality, Storage & RAM, Price & affordability, Brand reputation, After-Sales Service',
       'Storage & RAM, Price & affordability, Brand reputation, 5G support, Software & UI Experience',
       'Processor performance, Display quality, Storage & RAM',
       'Battery life, Display quality, Brand reputation',
       'Camera quality, Battery life, Processor performance, Display quality, Storage & RAM',
       'Camera quality, Display quality, 5G support',
       'Battery life, Processor performance, 5G support',
       'Camera quality, Processor performance, 5G support',
       'Camera quality, 5G support, Software & UI Experience',
       'Camera quality, Battery life, Processor performance, Display quality, 5G support',
       'Camera quality, Display quality, Brand reputation',
       'Display quality, Price & affordability, 5G support',
       'Processor performance, Brand reputation, Software & UI Experience',
       'Camera quality, Battery life, Display quality, Storage & RAM',
       'Processor performance, Storage & RAM, Price & affordability',
       'Camera quality, Battery life, Storage & RAM, Price & affordability',
       'Battery life, Price & affordability, After-Sales Service',
       'Camera quality, Battery life, Processor performance, Display quality, Storage & RAM, Price & affordability, Brand reputation, 5G support, Software & UI Experience',
       'Brand reputation',
       'Camera quality, Battery life, Display quality, Storage & RAM, 5G support, Software & UI Experience, After-Sales Service',
       'Camera quality, Battery life, Processor performance, Display quality',
       'Battery life, Storage & RAM, Price & affordability',
       'Camera quality, Battery life', 'Processor performance',
       'Camera quality, Battery life, Processor performance, Display quality, Storage & RAM, Price & affordability, Brand reputation, Software & UI Experience',
       'Camera quality, Display quality, Brand reputation, 5G support, Software & UI Experience',
       'Battery life, Price & affordability, 5G support',
       'Battery life, 5G support, Software & UI Experience',
       'Battery life, Display quality, Storage & RAM, Brand reputation',
       'Camera quality, Processor performance, Storage & RAM, Brand reputation, 5G support, After-Sales Service',
       'Battery life, Display quality, Software & UI Experience',
       'Camera quality, Display quality',
       'Camera quality, Processor performance, Display quality, Brand reputation',
       'Processor performance, Price & affordability, Software & UI Experience',
       'Battery life, Storage & RAM, 5G support',
       'Display quality, Storage & RAM, 5G support',
       'Camera quality, Processor performance, Display quality',
       'Camera quality, Processor performance, Price & affordability',
       'Camera quality, Battery life, Display quality, Software & UI Experience',
       'Battery life, Price & affordability, Brand reputation',
       'Battery life, Display quality, Price & affordability',
       'Camera quality, Processor performance, Brand reputation, 5G support, Software & UI Experience, After-Sales Service',
       'Camera quality, Storage & RAM, Price & affordability, 5G support',
       'Battery life, Storage & RAM, Software & UI Experience',
       'Battery life, Processor performance, Display quality, Storage & RAM, Brand reputation, 5G support, Software & UI Experience',
       'Camera quality, Battery life, Processor performance, Storage & RAM, Brand reputation, 5G support, Software & UI Experience',
       'Battery life, Processor performance, Software & UI Experience',
       '5G support, Software & UI Experience, After-Sales Service',
       'Battery life, Processor performance, Display quality',
       'Price & affordability, Software & UI Experience, After-Sales Service',
       'Camera quality, Brand reputation, After-Sales Service',
       'Camera quality, Processor performance, Storage & RAM, Brand reputation, 5G support, Software & UI Experience',
       'Processor performance, Price & affordability, After-Sales Service',
       'Battery life, Processor performance, Display quality, Storage & RAM, Price & affordability',
       'Camera quality, Battery life, Processor performance, Display quality, Software & UI Experience',
       'Camera quality, Battery life, Storage & RAM, 5G support, After-Sales Service',
       'Battery life, Processor performance, Price & affordability, Software & UI Experience',
       'Display quality',
       'Display quality, Storage & RAM, Price & affordability, 5G support',
       'Camera quality, Storage & RAM, Software & UI Experience, After-Sales Service',
       'Camera quality, Battery life, Processor performance, Display quality, Storage & RAM, Price & affordability, Brand reputation, Software & UI Experience, After-Sales Service',
       'Camera quality, Storage & RAM, Software & UI Experience',
       'Camera quality, Processor performance, Display quality, Storage & RAM, Brand reputation, Software & UI Experience',
       'Camera quality, Display quality, Price & affordability, Brand reputation, 5G support, Software & UI Experience',
       'Camera quality, Display quality, Price & affordability',
       'Battery life, Storage & RAM, After-Sales Service',
       'Camera quality, Display quality, Storage & RAM, Price & affordability, 5G support',
       'Battery life, Processor performance, Price & affordability, 5G support',
       'Display quality, Brand reputation, Software & UI Experience',
       'Camera quality, Battery life, Processor performance, Storage & RAM, Price & affordability'],
      dtype=object)

In [1500]:
manual_df['next_priority'].unique()

array([ 5.,  4.,  3.,  6.,  1.,  2., nan])

In [1501]:
map_next_priority ={
    1:'Budget/ Price',
    2:'Brand reputation',
    3:'Features (camera, battery, performance, etc)',
    4:'5G support',
    5:'Software updates & longevity',
    6:'Performance & Speed'
}

manual_df['next_priority']= manual_df['next_priority'].map(map_next_priority)

In [1502]:
manual_df['next_priority'].unique()

array(['Software updates & longevity', '5G support',
       'Features (camera, battery, performance, etc)',
       'Performance & Speed', 'Budget/ Price', 'Brand reputation', nan],
      dtype=object)

In [1503]:
online_df['next_priority'].unique()

array(['Brand reputation', 'Software updates & longevity',
       'Features ( camera, battery, performance,etc)', 'Budget/ Price',
       '5G support', 'Performance & Speed',
       'Features ( camera, battery, performance,etc)/ वैशिष्ट्ये (कॅमेरा, बॅटरी, कार्यप्रदर्शन इ.)',
       'Brand reputation/ ब्रँड प्रतिष्ठा', 'Budget/ Price/ बजेट/किंमत',
       'Performance & Speed/ परफॉर्मंस & स्पीड', '5G support/ 5G सपोर्ट',
       nan,
       'Software updates & longevity/ सॉफ्टवेअर अपडेट्स आणि दीर्घायुष्य'],
      dtype=object)

In [1504]:
priority_map = {
    'brand reputation': 'Brand reputation',
    'ब्रँड प्रतिष्ठा': 'Brand reputation',

    'software updates & longevity': 'Software updates & longevity',
    'सॉफ्टवेअर अपडेट्स आणि दीर्घायुष्य': 'Software updates & longevity',

    'features ( camera, battery, performance,etc)': 'Features (camera, battery, performance, etc)',
    'वैशिष्ट्ये (कॅमेरा, बॅटरी, कार्यप्रदर्शन इ.)': 'Features (camera, battery, performance, etc)',

    'budget/ price': 'Budget/ Price',
    'बजेट/किंमत': 'Budget/ Price',

    '5g support': '5G support',
    '5g सपोर्ट': '5G support',

    'performance & speed': 'Performance & Speed',
    'परफॉर्मंस & स्पीड': 'Performance & Speed'
}

In [1505]:
def clean_next_priority(value):
    if pd.isna(value):
        return None

    val = value.lower()

    for key in priority_map:
        if key in val:
            return priority_map[key]

    return 'Other'

In [1506]:
online_df['next_priority'] = online_df['next_priority'].apply(clean_next_priority)

In [1507]:
online_df['next_priority'].unique()

array(['Brand reputation', 'Software updates & longevity',
       'Features (camera, battery, performance, etc)', 'Budget/ Price',
       '5G support', 'Performance & Speed', None], dtype=object)

In [1508]:
manual_df['comments'].unique()

array([nan, 'camera quality', 'Extra Ram', 'Battery back up', 'no',
       'additional feature for gaming', 'additional feature'],
      dtype=object)

In [1509]:
online_df['comments'].unique()

array([nan, 'No', 'Good working ',
       'Smartphone should be value for money ', '... ',
       'Good experience ', 'Smart in best supporter for study',
       'Nothing ', '-', 'I am satisfied my smartphone', 'Nothing else ',
       'Good ', '.', "I'll choose camera quality for my own interest ",
       'No any comments', 'Best software ', 'Camera quality', 'Yes',
       'If buying online check for physical damage, screen issues and hardware defects immediately',
       'I like powerful processer ', 'All the best', 'Happy customer ',
       'Getting will add new features',
       'Brand . Quality expectations.and Best experience', 'नाही',
       ' Nahi',
       'Its very good experience and i know about it so i choose it wisely. ',
       '...',
       'वर्धित संवाद, माहितीचा सहज प्रवेश आणि दैनंदिन कामे व्यवस्थापित करण्याची सोय',
       'job lagel tewa..!! dream phone gheu.. aaplya paise ne ',
       "This is my first phone and this my brother's old phone , that's why I have no experience ",
       'Only nice quality i want', 'Nothing specific ', "It's good ",
       '5g ', 'More additional features 5G smartphone ',
       ' Online mobile one year Garanti aste', 'Nahi ', '5g',
       'स्माटफोन कामा पूरता वपरावे जास्त यूस कल्याणी माणुस डिप्रेशन मध्य जात ',
       'Buy any product with your own money and do not take any advice from anyone',
       "Best' 👍🏻😊", 'use',
       'Mobile battery life best and camera quality is best',
       ' When you buy  you getting update about additional feature and at all',
       'Smartphone is best for your bright future ',
       'Highest storage,high performance ', 'Camera ', 'Nahi', 'Quality ',
       "In today's life smartphone become an individual part of human ,but more than use of smart phone became dangerous for us , use it when you need .\n",
       'It is very expensive ', 'Ok', 'Use smart phone carefully',
       'Good experience good experience ', 'Expect', 'nahi',
       'Already using foldable smart phone.', 'No comments ',
       'No expectations...',
       'I want to use the smartphone for gaining knowledge ', 'Nothing',
       'Hdjd', 'Free gifts on phone ', 'No experience ', ' Good',
       'Good quality ',
       'Now mobile is necessary for communication,intertenment, knowledge ',
       'Buy the smartphones on their camera & speed performance.',
       'Now days smartphone are not that compact. I like compact and light weight smartphones. Smartphone brands are just following a trend of big camera and screen. They should focus on some other things now. Now days they forget about compact phones.',
       'Worrnety or display ', 'Camera or sound', 'Ram storage ',
       'Smartphone should be affordable and should have high performance.',
       'Mobali cha dispel chagla pahije \n\n\n', 'Budge price ',
       'Display', '1 years ',
       'I wish I could gel the smartphone which I want to buy next !! ',
       'For Great quality of software \n'], dtype=object)

In [1510]:
manual_df['email'].unique()

array([nan])

In [1511]:
online_df['email'].unique()

array([nan, 'gosavimadhuri95@gmail.com', 'viru88018@gmail.com',
       'patilvasudha353@gmail.com', 'ssrajputshubham00@gmail.com',
       'harshadagsalunkhe195@gmail.com', 'hiteshdeore202552@gmail.com',
       'swatibadgujar473@gmail.com', 'dikshabhamare2203@gmail.com',
       'nirjarahire@gmail.com', 'bhaveshbhamare27@gmail.com',
       'shwetadjain2404@gmail.com', 'nikitarajput2004@gmail.com',
       'sdd.spdm@gmail.com', 'firdos.dhule@gmail.com',
       'rajputsanyogita671@gmail.com', 'rajashrimore037@gmail.com',
       'madhuriragade818@gmail.com', 'harshalrajput812@gmail.com',
       'udesinggirase887@gmail.com', 'gosavidamini370@gmail.com',
       'sakshigirase77@gmail.com', 'vaishnavirajput1425@gmail.com',
       'nsharajput198119@gmail.com', 'mrunalispatil2004@gmail.com',
       'pratikrajputt1997@gmail.com', 'premmali1221@gmail.com',
       'sunilrajput253@gmail.com', 'manaswirawal@gmail.com',
       'gp9470913@gmail.com', 'savantom777@gmail.com',
       'sachinsonaje75@gmail.com', 'artipatil9881@gmail.com',
       'deoretanvi13@gmail.com', 'patilrahul6715@gmail.com',
       'rajshirsath444@gmail.com', 'mayurpatil1548@gmail.com',
       'patilmadhuri95604@gmail.com', 'sp546625@gmail.com',
       'gargichavan78@gmail.com', 'ar5641269@gmail.com',
       'yadnyashrinandre@gmail.com', 'shivamb252002@gmail.com',
       'sp9430505@gmail.com', 'rutik5905@gmail.com',
       'sagarjdhv5@gmail.com', 'pkoli3360@gmail.com',
       'vanshitabhavsar95@gmail.com', 'mr8888472@gmail.com',
       'vaishnavidorik@gmail.com', 'giraseyogesh97@gmail.com',
       'harshalwadile837@gmail.com', 'ajit.new137@gmail.com',
       'divya20051610@gmail.com', 'shirsathsachin498@gmail.com',
       'rajputdhanashri5@gmail.com', 'girasetrupti2@gmail.com',
       'bhaveshborase265@gmail.com', 'morenikhil1009@gmail.com',
       'poojarandive1004@gmail.com', 'gayatrivispute110@gmail.com',
       'patilashwini2408@gmail.com', 'harshitakulkarni2004@gmail.com',
       'attarirfan2004@gmail.com', 'khalil3818sk@gmail.com',
       'mayurtholbare123@gmail.com', 'pawarbhagwati72@gmail.com',
       'wagha025@gmail.com', 'bhadangemeghana394@gmail.com',
       'mr8863994@gmail.com', 'tejalborse2003@gmail.com',
       'janavivbadgujar111@gmail.com', 'harshda259@gmail.com',
       'pranavnc004@gmail.com', 'nikhira2005@gmail.com',
       'dikshagirase92@gmail.com', 'chaudharikritika23@gmail.com',
       'sonakshibadgujar2007@gmail.com', 'tinashimpi1@gmail.com',
       'shreyaskhairmar124@gmail.com', 'ajayishi13@gmail.com',
       'sisodiyatejasvini@gmail.com', 'pratiksharruikar@gmail.com',
       'akshaypatil05122000@gmail.com', 'patilbhavesh9655@gmail.com',
       'suryawanshikishor51@gmail.com', 'mansvipatil272005@gmail.com',
       'haddeshwaarig@gmail.com', 'nikhilrajput8767@gmail.com',
       'madhavipatil09876@gmail.com', 'pharshu811@gmail.com',
       'yashpatilpatil07@gmail.com', 'sachinthakare9195@gmail.com',
       'lp120705@gmail.com', 'rkgosavi3120@gmail.com',
       'swayampatil2010@gmail.com', 'divyashimpi99@gmail.com',
       'pankajpatil007@gmail.com', 'pawararavindra658@gmail.com',
       'bhogenivrutti07@gmail.com', 'sutarumesha@gmail.com',
       'vishaljpatil2000@gmail.com', 'yeoletanmay4950@gmail.com',
       'badgujar2005@gmail.com', 'manyatajain714@gmail.com',
       'kp0410614@gmail.com', 'pravindchavan6@gmail.com',
       'pranjalpatil8830@gmail.com', 'ravindrasonar805@gamil.com',
       'rohanwakode234@gmail.com', 'patildiu35@gmail.com',
       'akashgosavi9591@gmail.com', 'vrushabh150150@gmail.com',
       'bawabhushan64@gmail.com', 'landgeaniruddha7@gmail.com',
       'vijay.chaudhari8118@gmail.com', 'sumitbari1695@gmail.com',
       'pawarpiyush704@gmail.com', 'salunkhekishor1999@gmail.com',
       'praveen.girase79@gmail.com', 'rajputpriyank4400@gmail.com',
       'nilnanda93@gmail.com', 'rohitraviraj1995@gmail.com',
       'yadneshrajput812@gmail.com', 'gayatrirajput2004@gmail.com',
       'ravindrasonar076@gamil.com', 'rdlscanning751@gmail.com',
       'satishthore4626a@gmail.com', 'riyanjawale99@gmail.com',
       'vaibhavshimpi06@gmail.com', 'ganeshragade8832@gmail.com',
       'patilnikita1412@gmail.com', 'hemant.rajput747@gmail.com',
       'swatirajput1974@gmail.com', 'meghajain372000@gmail.com',
       'rharshada675@gmail.com', 'ranirajput8164@gmail.com',
       'rajputnarendrasing503@gmail.com', 'rrajput61707@gmail.com',
       'ugirase2266@gmail.com', 'dharmarajrajput64@gmail.com',
       'riteshrajput49857@gmail.com', 'jayurajput57@gmail.com',
       'devadadaurajput@gmail.com', 'rajputprakasha1970@gmail.com',
       'dinesherajput32858@gmail.com', 'rajputprathamesh757@gmail.com',
       'digvijayrajput2238@gmail.com', 'kamaleshmore4@gmail.com',
       'renukarajput425@gmail.com', 'aniketmore3558@gmail.com',
       'shitalsonawane1904@gmail.com', 'pratikborse9876@gmail.com',
       'ruchikagujar3504@gmail.com', 'rajputnandini214@gmail.com',
       'dhruvhadhav888@gmail.com', 'vip551@gmail.com',
       'mamtarajput1978@gmail.com', 'mohinirajput2004@gmail.com',
       'nileshshah6033@gmail.com', 'harshadapatil61199@gmail.com',
       'prempatil2387@gmil.com', 'snehapatil0104@gmail.com',
       'vaishnavip806@gmail.com', 'patilnileshs8620@gmail.com',
       'thakareakash965@gmail.com', 'bhaveshshirsath43@gmail.com',
       'moreabhitaysanjay@gmail.com', 'ketyraj83@gmail.com',
       'mayurpatil567@gmail.com', 'shubhamapatil@gmail.com',
       'kishorkumarrajput1987@gmail.com', 'indradipsingh25@gmail.com',
       'rajputshivangi047@gmail.com', 'omrajput4231@gmail.com',
       '44sohan@gmail.com', 'jadhavdhiraj190@gmail.com',
       'mitesh.pagare.37@gmail.com', 'khuterohan1705@gmail.com',
       'unnatirajput@gmail.com', 'abhayarajput12@gmail.com',
       'chetanjadhav@gmail.com', 'pbj456@gmail.com', 'vr9034@gmail.com',
       'madhurijadhav@gmail.com', 'soniraj@gmail.com',
       'princejain@gmail.com', 'mamtajain@gmail.com',
       'jayamjain@gmail.com', 'mahalekavita347@gmail.com',
       'hitu.deshmukh@gmail.com', 'manasisaner56@gmail.com',
       'premjeetgirase@gmail.com', 'riyachaudhari343@gmail.com',
       'msonawane6114@gmail.com', 'himanip075@gmail.com',
       'kiranpatil.skill.2004@gmail.com', 'dishapatil6227@gmail.com',
       'darshanagaikwad43@gmail.com', 'himanipatil055@gmail.com',
       'vibhavarisutar7@gmail.com', 'harshajain2106@gmail.com',
       'sejalchaudhari060@gmail.com', 'bsnehal270@gmail.com',
       'ap7647596@gmail.com', 'dikshachaudhari211@gmail.com',
       'divyapatil31912@gmail.com', 'sg123@gmail.con',
       'kaminipatil5102004@gmail.com', 'riddhigindodiya10@gmail.com',
       'munazzaansari380@gmail.com', 'dp2007613@gmail.com',
       'yojanamandavade@gmail.com', 'rohidasp336@mail.com',
       'vdj223456@gmail.com', 'shirikat@gmail.com',
       'gorakhpatil923@gmail.com', 'akshaychavan06012001@gmail.com',
       'krutikapatil1935@gmail.com', 'truptichavan2504@gmail.com',
       'badgujarpranjali@gmail.com', 'badgujarvaishnavi62@gmail.com',
       'sanikabadgujar9922@gmail.com', 'harshyaapatil18@gmail.com',
       'himanshupatil45h@gmail.com', 'chetanpatil6969@gmail.com',
       'mohiteashish621@gmail.com', 'nutanbhadane2003@gmail.com',
       'vaishalichavan915@gmail.com', 'baviskarpooja2410@gmail.com',
       'fasiddiqui.12q@gmail.com', 'joshisurbhi207@gmail.com',
       'gauravpatil8708@gmail.com', 'gauravpawar7970@gmail.com',
       'lalitbarakuborse111@gmail.com', 'punampatil9767@gmail.com',
       'patilkalpesh0720@gmail.com', 'pratikshapatil756@gmail.com',
       'khondebhushan82@gmail.com', 'ayushahire48@gmail.com',
       'khushi24450@gmail.com', 'mahimaraj@gmail.com',
       'mr8863990@gmail.com', 'nandinishimpi143@gmail.com',
       'chandrakantparaskar3643@gmail.com', 'ketansharma5634@gmail.com',
       'sarangdeore@gmail.com', 'harshnarawal95@gmail.com',
       'patilpayal8599@gmail.com'], dtype=object)

In [1512]:
manual_df.columns

Index(['name', 'age_group', 'gender', 'residential_area', 'location_name',
       'education_level', 'employment_status', 'monthly_income',
       'current_brand', 'model_name', 'current_price_range', 'usage_duration',
       'purchase_source', 'top_3_reasons', 'most_used_feature',
       'upgrade_frequency', 'purchase_preference', 'resale_consideration',
       'satisfaction', 'next_brand_preference', 'next_priority', 'next_budget',
       'foldable_interest', 'indian_brand_preference', 'comments', 'email'],
      dtype='object')

In [1513]:
manual_df.drop(columns=['name','email','comments'],inplace=True)

In [1514]:
manual_df.columns

Index(['age_group', 'gender', 'residential_area', 'location_name',
       'education_level', 'employment_status', 'monthly_income',
       'current_brand', 'model_name', 'current_price_range', 'usage_duration',
       'purchase_source', 'top_3_reasons', 'most_used_feature',
       'upgrade_frequency', 'purchase_preference', 'resale_consideration',
       'satisfaction', 'next_brand_preference', 'next_priority', 'next_budget',
       'foldable_interest', 'indian_brand_preference'],
      dtype='object')

In [1515]:
online_df.columns

Index(['timestamp', 'age_group', 'gender', 'residential_area',
       'employment_status', 'monthly_income', 'current_brand',
       'current_price_range', 'usage_duration', 'purchase_source',
       'top_3_reasons', 'upgrade_frequency', 'purchase_preference',
       'resale_consideration', 'next_priority', 'foldable_interest',
       'indian_brand_preference', 'satisfaction', 'next_brand_preference',
       'comments', 'model_name', 'education_level', 'next_budget',
       'most_used_feature', 'location_name', 'email'],
      dtype='object')

In [1516]:
online_df.drop(columns= ['timestamp'],inplace=True)

In [1517]:
online_df.columns

Index(['age_group', 'gender', 'residential_area', 'employment_status',
       'monthly_income', 'current_brand', 'current_price_range',
       'usage_duration', 'purchase_source', 'top_3_reasons',
       'upgrade_frequency', 'purchase_preference', 'resale_consideration',
       'next_priority', 'foldable_interest', 'indian_brand_preference',
       'satisfaction', 'next_brand_preference', 'comments', 'model_name',
       'education_level', 'next_budget', 'most_used_feature', 'location_name',
       'email'],
      dtype='object')

In [1518]:
online_df.drop('location_name', axis=1, inplace=True)

In [1519]:
manual_df.drop('location_name', axis=1, inplace=True)

In [1520]:
manual_df

,age_group,gender,residential_area,education_level,employment_status,monthly_income,current_brand,model_name,current_price_range,usage_duration,...,most_used_feature,upgrade_frequency,purchase_preference,resale_consideration,satisfaction,next_brand_preference,next_priority,next_budget,foldable_interest,indian_brand_preference
0,36 - 50,Female,Rural,Graduation,Employed,"10,000 - 25,000",Xiaomi,redmi 6,"Below 10,000",More than 3 years,...,Office works,Only when my phone stops working,Online,No,Yes,Samsung,Software updates & longevity,"20,000 - 40,000",No,Yes
1,18 - 25,Female,Rural,Graduation,Student,"10,000 - 25,000",Vivo,vivo y20,"10,000 - 20,000",More than 3 years,...,Communication,Only when my phone stops working,Offline (Retail Store),Yes,No,Vivo,5G support,"10,000 - 20,000",Maybe,Doesn't matter
2,18 - 25,Female,Rural,Graduation,Student,"25,000 - 50,000",Vivo,vivo y200e 5g,"20,000 - 40,000",6 months - 1 year,...,Social media,Every 3+ years,Offline (Retail Store),No,Yes,OnePlus,"Features (camera, battery, performance, etc)","20,000 - 40,000",No,Yes
3,26 - 35,Male,Rural,Post-graduation & Above,Employed,"10,000 - 25,000",Vivo,vivo y73,"20,000 - 40,000",1 - 3 years,...,Office works,Every 2 years,Offline (Retail Store),Yes,No,Unknown,Performance & Speed,"20,000 - 40,000",Maybe,Doesn't matter
4,18 - 25,Female,Rural,Post-graduation & Above,Student,"10,000 - 25,000",Realme,realme narzo 50a,"10,000 - 20,000",1 - 3 years,...,Communication,Every 3+ years,Offline (Retail Store),No,Yes,Oppo,5G support,"20,000 - 40,000",No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,18 - 25,Male,Rural,Post-graduation & Above,Student,"10,000 - 25,000",Xiaomi,redmi 9 prime,"Below 10,000",1 - 3 years,...,Camera,Every year,Whichever gives the best deal,No,Yes,Samsung,Software updates & longevity,"40,000 - 70,000",No,No
97,18 - 25,Male,Rural,Below 10th,Self-Employed,"Below 10,000",Vivo,vivo,"10,000 - 20,000",1 - 3 years,...,Social media,Every 3+ years,Online,Yes,Yes,Apple,"Features (camera, battery, performance, etc)","40,000 - 70,000",Yes,No
98,26 - 35,Female,Rural,Graduation,Self-Employed,"10,000 - 25,000",Samsung,samsung,"10,000 - 20,000",Less than 6 months,...,Communication,Every 2 years,Offline (Retail Store),Yes,No,Google,Brand reputation,"Below 10,000",Maybe,Doesn't matter
99,18 - 25,Female,Urban,Post-graduation & Above,Unemployed,"50,000 - 1,00,000",Oppo,oppo a54,"40,000 - 70,000",1 - 3 years,...,Communication,Every year,Online,No,No,Google,Budget/ Price,"10,000 - 20,000",Maybe,Yes
100,18 - 25,Female,Rural,10th - 12th,Employed,"25,000 - 50,000",Oppo,oppo,"Below 10,000",More than 3 years,...,Social media,Every year,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN

In [1521]:
manual_df.columns

Index(['age_group', 'gender', 'residential_area', 'education_level',
       'employment_status', 'monthly_income', 'current_brand', 'model_name',
       'current_price_range', 'usage_duration', 'purchase_source',
       'top_3_reasons', 'most_used_feature', 'upgrade_frequency',
       'purchase_preference', 'resale_consideration', 'satisfaction',
       'next_brand_preference', 'next_priority', 'next_budget',
       'foldable_interest', 'indian_brand_preference'],
      dtype='object')

In [1522]:
online_df.columns

Index(['age_group', 'gender', 'residential_area', 'employment_status',
       'monthly_income', 'current_brand', 'current_price_range',
       'usage_duration', 'purchase_source', 'top_3_reasons',
       'upgrade_frequency', 'purchase_preference', 'resale_consideration',
       'next_priority', 'foldable_interest', 'indian_brand_preference',
       'satisfaction', 'next_brand_preference', 'comments', 'model_name',
       'education_level', 'next_budget', 'most_used_feature', 'email'],
      dtype='object')

In [1523]:
online_df.drop(columns= ['comments', 'email'],inplace=True)

In [1524]:
online_df

,age_group,gender,residential_area,employment_status,monthly_income,current_brand,current_price_range,usage_duration,purchase_source,top_3_reasons,...,resale_consideration,next_priority,foldable_interest,indian_brand_preference,satisfaction,next_brand_preference,model_name,education_level,next_budget,most_used_feature
0,36 - 50,Female,Rural,Student,"Below 10,000",Nokia,"20,000 - 40,000",Less than 6 months,Online,"Camera quality, Processor performance, Display...",...,Yes,Brand reputation,Maybe,Doesn't matter,Yes,Oppo,redmi note. 6 pro,Below 10th,"10,000 - 20,000",Web browsing
1,18 - 25,Male,Urban,Student,"Below 10,000",Xiaomi,"10,000 - 20,000",6 months - 1 year,Local Retail Store,"Camera quality, Battery life, Processor perfor...",...,Yes,Software updates & longevity,Maybe,Yes,No,Unknown,redmi,Graduation,"20,000 - 40,000",Social media
2,18 - 25,Female,Rural,Student,"25,000 - 50,000",Xiaomi,"10,000 - 20,000",1 - 3 years,Local Retail Store,"Camera quality, Storage & RAM, Brand reputation",...,Yes,"Features (camera, battery, performance, etc)",No,Yes,Yes,OnePlus,redmi note 6 pro,Graduation,"20,000 - 40,000",Web browsing
3,18 - 25,Male,Rural,Self-Employed,"25,000 - 50,000",Oppo,"Below 10,000",More than 3 years,Local Retail Store,After-Sales Service,...,Yes,Budget/ Price,Yes,Yes,No,Unknown,None,Graduation,"Below 10,000",Other
4,18 - 25,Female,Rural,Student,"25,000 - 50,000",Realme,"10,000 - 20,000",More than 3 years,Online,"Camera quality, Storage & RAM, Price & afforda...",...,No,5G support,Yes,Yes,Yes,Realme,realme 5- pro,Graduation,"20,000 - 40,000",Communication
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,26 - 35,Male,Rural,Self-Employed,"25,000 - 50,000",Vivo,"40,000 - 70,000",1 - 3 years,Brand Outlet/Showroom,"Display quality, Brand reputation, Software & ...",...,Yes,Software updates & longevity,No,Yes,No,Redmi,vivo v14,Graduation,"10,000 - 20,000",Web browsing
255,18 - 25,Male,Rural,Employed,"25,000 - 50,000",Nokia,"10,000 - 20,000",1 - 3 years,Brand Outlet/Showroom,"Battery life, Display quality, Brand reputation",...,Yes,Brand reputation,No,No,No,Vivo,nokia k9,Graduation,"20,000 - 40,000",Social media
256,18 - 25,Female,Urban,Student,"10,000 - 25,000",Oppo,"10,000 - 20,000",1 - 3 years,Local Retail Store,"Camera quality, Battery life, Processor perfor...",...,No,Brand reputation,Maybe,Yes,Yes,Oppo,oppo 1+,10th - 12th,"10,000 - 20,000",Other
257,26 - 35,Female,Urban,Self-Employed,"50,000 - 1,00,000",OnePlus,"20,000 - 40,000",More than 3 years,Local Retail Store,"Camera quality, Battery life, Processor perfor...",...,No,Budget/ Price,No,Yes,Yes,Apple,oneplus nord 2 5g,Post-graduation & Above,"20,000 - 40,000",Communication
258,18 - 25,Female,Rural,Student,"25,000 - 50,000",Xiaomi,"10,000 - 20,000",6 months - 1 year,Local Retail Store,"Camera quality, Battery life, 5G support",...,No,"Features (camera, battery, performance, etc)",Maybe,Yes,Yes,Redmi,redmi 13c,Graduation,"10,000 - 20,000",Social media

In [1525]:
combined_df = pd.concat([manual_df, online_df], ignore_index=True)

In [1526]:
combined_df

,age_group,gender,residential_area,education_level,employment_status,monthly_income,current_brand,model_name,current_price_range,usage_duration,...,most_used_feature,upgrade_frequency,purchase_preference,resale_consideration,satisfaction,next_brand_preference,next_priority,next_budget,foldable_interest,indian_brand_preference
0,36 - 50,Female,Rural,Graduation,Employed,"10,000 - 25,000",Xiaomi,redmi 6,"Below 10,000",More than 3 years,...,Office works,Only when my phone stops working,Online,No,Yes,Samsung,Software updates & longevity,"20,000 - 40,000",No,Yes
1,18 - 25,Female,Rural,Graduation,Student,"10,000 - 25,000",Vivo,vivo y20,"10,000 - 20,000",More than 3 years,...,Communication,Only when my phone stops working,Offline (Retail Store),Yes,No,Vivo,5G support,"10,000 - 20,000",Maybe,Doesn't matter
2,18 - 25,Female,Rural,Graduation,Student,"25,000 - 50,000",Vivo,vivo y200e 5g,"20,000 - 40,000",6 months - 1 year,...,Social media,Every 3+ years,Offline (Retail Store),No,Yes,OnePlus,"Features (camera, battery, performance, etc)","20,000 - 40,000",No,Yes
3,26 - 35,Male,Rural,Post-graduation & Above,Employed,"10,000 - 25,000",Vivo,vivo y73,"20,000 - 40,000",1 - 3 years,...,Office works,Every 2 years,Offline (Retail Store),Yes,No,Unknown,Performance & Speed,"20,000 - 40,000",Maybe,Doesn't matter
4,18 - 25,Female,Rural,Post-graduation & Above,Student,"10,000 - 25,000",Realme,realme narzo 50a,"10,000 - 20,000",1 - 3 years,...,Communication,Every 3+ years,Offline (Retail Store),No,Yes,Oppo,5G support,"20,000 - 40,000",No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,26 - 35,Male,Rural,Graduation,Self-Employed,"25,000 - 50,000",Vivo,vivo v14,"40,000 - 70,000",1 - 3 years,...,Web browsing,Every 2 years,Brand Showroom,Yes,No,Redmi,Software updates & longevity,"10,000 - 20,000",No,Yes
356,18 - 25,Male,Rural,Graduation,Employed,"25,000 - 50,000",Nokia,nokia k9,"10,000 - 20,000",1 - 3 years,...,Social media,Every 3+ years,Brand Showroom,Yes,No,Vivo,Brand reputation,"20,000 - 40,000",No,No
357,18 - 25,Female,Urban,10th - 12th,Student,"10,000 - 25,000",Oppo,oppo 1+,"10,000 - 20,000",1 - 3 years,...,Other,Only when my phone stops working,Brand Showroom,No,Yes,Oppo,Brand reputation,"10,000 - 20,000",Maybe,Yes
358,26 - 35,Female,Urban,Post-graduation & Above,Self-Employed,"50,000 - 1,00,000",OnePlus,oneplus nord 2 5g,"20,000 - 40,000",More than 3 years,...,Communication,Only when my phone stops working,Whichever gives the best deal,No,Yes,Apple,Budget/ Price,"20,000 - 40,000",No,Yes
359,18 - 25,Female,Rural,Graduation,Student,"25,000 - 50,000",Xiaomi,redmi 13c,"10,000 - 20,000",6 months - 1 year,...,Social media,Only when my phone stops working,Offline (Retail Store),No,Yes,Redmi,"Features (camera, battery, performance, etc)","10,000 - 20,000",Maybe,Yes

In [1527]:
# Step 1: Add sr_no column (starts from 1)
combined_df.insert(0, 'sr_no', range(1, len(combined_df) + 1))

In [1528]:
# Step 2: Save to CSV
combined_df.to_csv("cleaned_Survey_Responses_dataset.csv", index=False)

In [1529]:
combined_df

,sr_no,age_group,gender,residential_area,education_level,employment_status,monthly_income,current_brand,model_name,current_price_range,...,most_used_feature,upgrade_frequency,purchase_preference,resale_consideration,satisfaction,next_brand_preference,next_priority,next_budget,foldable_interest,indian_brand_preference
0,1,36 - 50,Female,Rural,Graduation,Employed,"10,000 - 25,000",Xiaomi,redmi 6,"Below 10,000",...,Office works,Only when my phone stops working,Online,No,Yes,Samsung,Software updates & longevity,"20,000 - 40,000",No,Yes
1,2,18 - 25,Female,Rural,Graduation,Student,"10,000 - 25,000",Vivo,vivo y20,"10,000 - 20,000",...,Communication,Only when my phone stops working,Offline (Retail Store),Yes,No,Vivo,5G support,"10,000 - 20,000",Maybe,Doesn't matter
2,3,18 - 25,Female,Rural,Graduation,Student,"25,000 - 50,000",Vivo,vivo y200e 5g,"20,000 - 40,000",...,Social media,Every 3+ years,Offline (Retail Store),No,Yes,OnePlus,"Features (camera, battery, performance, etc)","20,000 - 40,000",No,Yes
3,4,26 - 35,Male,Rural,Post-graduation & Above,Employed,"10,000 - 25,000",Vivo,vivo y73,"20,000 - 40,000",...,Office works,Every 2 years,Offline (Retail Store),Yes,No,Unknown,Performance & Speed,"20,000 - 40,000",Maybe,Doesn't matter
4,5,18 - 25,Female,Rural,Post-graduation & Above,Student,"10,000 - 25,000",Realme,realme narzo 50a,"10,000 - 20,000",...,Communication,Every 3+ years,Offline (Retail Store),No,Yes,Oppo,5G support,"20,000 - 40,000",No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,356,26 - 35,Male,Rural,Graduation,Self-Employed,"25,000 - 50,000",Vivo,vivo v14,"40,000 - 70,000",...,Web browsing,Every 2 years,Brand Showroom,Yes,No,Redmi,Software updates & longevity,"10,000 - 20,000",No,Yes
356,357,18 - 25,Male,Rural,Graduation,Employed,"25,000 - 50,000",Nokia,nokia k9,"10,000 - 20,000",...,Social media,Every 3+ years,Brand Showroom,Yes,No,Vivo,Brand reputation,"20,000 - 40,000",No,No
357,358,18 - 25,Female,Urban,10th - 12th,Student,"10,000 - 25,000",Oppo,oppo 1+,"10,000 - 20,000",...,Other,Only when my phone stops working,Brand Showroom,No,Yes,Oppo,Brand reputation,"10,000 - 20,000",Maybe,Yes
358,359,26 - 35,Female,Urban,Post-graduation & Above,Self-Employed,"50,000 - 1,00,000",OnePlus,oneplus nord 2 5g,"20,000 - 40,000",...,Communication,Only when my phone stops working,Whichever gives the best deal,No,Yes,Apple,Budget/ Price,"20,000 - 40,000",No,Yes
359,360,18 - 25,Female,Rural,Graduation,Student,"25,000 - 50,000",Xiaomi,redmi 13c,"10,000 - 20,000",...,Social media,Only when my phone stops working,Offline (Retail Store),No,Yes,Redmi,"Features (camera, battery, performance, etc)","10,000 - 20,000",Maybe,Yes